// Bakes the force layout at build time (AD-3): runs d3-force to completion
// synchronously and writes src/data/layout.ts. The browser never simulates.
//
// Determinism: nodes and links enter sorted by id, the simulation's
// randomSource is seeded (splitmix32), tick count is fixed by the standard
// alpha schedule, and coordinates round to 1 decimal. Running twice must be
// byte-identical (tested in Phase 1 acceptance).
//
// Run: npm run data:layout

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  forceCollide,
  forceLink,
  forceManyBody,
  forceSimulation,
  forceX,
  forceY,
  type SimulationLinkDatum,
  type SimulationNodeDatum,
} from 'd3-force'
import { splitmix32 } from '../src/lib/prng.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const PATTERNS_PATH = join(root, 'src/data/patterns.ts')
const OUT_PATH = join(root, 'src/data/layout.ts')

// d3 types stay confined to this script (plan: schema.ts never extends them).
interface LayoutNode extends SimulationNodeDatum {
  id: number
}

// Canvas in abstract units; the renderer fits it to the viewport.
const WIDTH = 1000
const BAND = { towns: 250, buildings: 750, construction: 1250 } as const
const BAND_HALF = 230 // clamp: keeps every node inside its band's stratum
const SEED = 0x9a7031 // arbitrary, fixed forever

function bandOf(id: number): keyof typeof BAND {
  if (id <= 94) return 'towns'
  if (id <= 204) return 'buildings'
  return 'construction'
}

// --- Load the generated dataset (parse the JSON literal back out) --------
const ts = readFileSync(PATTERNS_PATH, 'utf8')
const inputHash = createHash('sha256').update(ts).digest('hex')
const match = ts.match(/= (\[[\s\S]*\]) satisfies/)
if (!match) throw new Error('cannot parse src/data/patterns.ts')
const patterns = JSON.parse(match[1]!) as {
  id: number
  narrower: number[]
}[]

const nodes: LayoutNode[] = patterns
  .map((p) => ({ id: p.id }))
  .sort((a, b) => a.id - b.id)
const links: SimulationLinkDatum<LayoutNode>[] = patterns
  .flatMap((p) => p.narrower.map((n) => ({ source: p.id, target: n })))
  .sort((a, b) =>
    (a.source as number) - (b.source as number) ||
    (a.target as number) - (b.target as number),
  )

// Deterministic phyllotaxis-like seeding inside each band (d3's default
// initializer depends on array order only, but being explicit costs nothing
// and keeps intent visible).
const rand = splitmix32(SEED)
for (const n of nodes) {
  n.x = (rand() - 0.5) * WIDTH
  n.y = BAND[bandOf(n.id)] + (rand() - 0.5) * BAND_HALF
}

const simulation = forceSimulation(nodes)
  .randomSource(splitmix32(SEED ^ 0x5f5f5f))
  .force(
    'link',
    forceLink<LayoutNode, SimulationLinkDatum<LayoutNode>>(links)
      .id((d) => d.id)
      .distance(60)
      .strength(0.08),
  )
  .force('charge', forceManyBody().strength(-80).distanceMax(300))
  .force('x', forceX(WIDTH / 2).strength(0.03))
  .force('y', forceY<LayoutNode>((d) => BAND[bandOf(d.id)]).strength(0.25))
  .force('collide', forceCollide(14).iterations(2))
  .stop()

const ticks = Math.ceil(
  Math.log(simulation.alphaMin()) / Math.log(1 - simulation.alphaDecay()),
)
for (let i = 0; i < ticks; i++) {
  simulation.tick()
  // Hard band clamp each tick: the y-force attracts, this guarantees.
  for (const n of nodes) {
    const center = BAND[bandOf(n.id)]
    if (n.y! < center - BAND_HALF) n.y = center - BAND_HALF
    if (n.y! > center + BAND_HALF) n.y = center + BAND_HALF
  }
}

const positions = Object.fromEntries(
  nodes.map((n) => [n.id, { x: Math.round(n.x! * 10) / 10, y: Math.round(n.y! * 10) / 10 }]),
)

const out = `// GENERATED by scripts/compute-layout.ts — do not edit by hand.
// Deterministic banded force layout (seed ${SEED}, ${ticks} ticks).
// inputHash guards against a layout baked from stale patterns.ts.
// Regenerate with: npm run data:layout

export const layoutInputHash =
  '${inputHash}'

export const positions: Readonly<Record<number, { x: number; y: number }>> =
  ${JSON.stringify(positions)}
`
writeFileSync(OUT_PATH, out)
console.log(`wrote ${OUT_PATH}: ${nodes.length} positions, ${ticks} ticks`)
