// Attributions and references (AD-5): the books, the metadata source, and
// the content stance. All prose here — like everywhere in the atlas — is
// original.

import { Link } from 'wouter'

const section = { marginTop: '1.6rem' } as const
const eyebrow = {
  fontVariantCaps: 'small-caps',
  letterSpacing: '0.08em',
  fontWeight: 'normal',
  fontSize: '0.9rem',
  color: 'var(--color-fade)',
  margin: '0 0 0.3rem',
} as const

export default function Colophon() {
  return (
    <main style={{ maxWidth: '38rem', margin: '0 auto', padding: '2rem 1rem 3rem' }}>
      <h1 style={{ fontWeight: 'normal' }}>Colophon</h1>
      <p style={{ color: 'var(--color-fade)' }}>
        <Link href="/">Back to the map</Link> ·{' '}
        <Link href="/patterns">the pattern index</Link>
      </p>

      <section style={section}>
        <h2 style={eyebrow}>the books</h2>
        <p>
          This atlas maps <em>A Pattern Language: Towns, Buildings,
          Construction</em> (Oxford University Press, 1977) by Christopher
          Alexander, Sara Ishikawa, and Murray Silverstein, with Max
          Jacobson, Ingrid Fiksdahl-King, and Shlomo Angel. The introduction
          draws on <em>The Timeless Way of Building</em> (Oxford University
          Press, 1979) by Christopher Alexander.
        </p>
        <p>
          What appears here is the books&rsquo; structure — pattern numbers,
          names, confidence asterisks, category headings, and the links
          between patterns. Those are facts about the works. Every sentence
          of prose in this atlas is original; none of the books&rsquo; text
          appears anywhere in it. The books remain the real thing, and they
          are worth owning.
        </p>
      </section>

      <section style={section}>
        <h2 style={eyebrow}>the data</h2>
        <p>
          Pattern metadata was extracted from{' '}
          <a href="https://github.com/zenodotus280/apl-md">apl-md</a>, a
          careful hand-transcription project maintained with the rights
          holder&rsquo;s permission. This atlas takes factual metadata only
          — names, numbers, asterisks, and link structure — pinned to a
          fixed commit and validated against the book. The layout, glyphs,
          building footprints, and marginal drawings are all generated by
          this project.
        </p>
      </section>

      <section style={section}>
        <h2 style={eyebrow}>the making</h2>
        <p>
          Built with React, TypeScript, Vite, and the d3 modules for zoom,
          force layout, and Voronoi tessellation. The map is deterministic:
          every position, district, and drawing is baked at build time from
          a fixed seed. Source:{' '}
          <a href="https://github.com/deerdear/pattern-atlas">
            github.com/deerdear/pattern-atlas
          </a>
          .
        </p>
      </section>
    </main>
  )
}
