// GENERATED by scripts/convert-graphml.ts — do not edit by hand.
// Source: data-notes/patterns.graphml (see data-notes/LICENSE-data for
// provenance and license). Prose gists come from data-notes/gists.json.
// Regenerate with: npm run data:convert

import type { Pattern, PatternData } from './schema'

export const patterns = [
  {
    "id": 1,
    "name": "Independent Regions",
    "confidence": 0,
    "category": "Regions",
    "broader": [],
    "narrower": [
      2,
      4,
      223
    ]
  },
  {
    "id": 2,
    "name": "The Distribution of Towns",
    "confidence": 0,
    "category": "Regions",
    "broader": [
      1
    ],
    "narrower": [
      3,
      6,
      7,
      223
    ]
  },
  {
    "id": 3,
    "name": "City Country Fingers",
    "confidence": 2,
    "category": "Regions",
    "broader": [
      2,
      5
    ],
    "narrower": [
      4,
      5,
      6,
      7,
      8,
      10,
      11,
      16
    ]
  },
  {
    "id": 4,
    "name": "Agricultural Valleys",
    "confidence": 1,
    "category": "Regions",
    "broader": [
      1,
      3
    ],
    "narrower": [
      7,
      8,
      16,
      17
    ]
  },
  {
    "id": 5,
    "name": "Lace of Country Streets",
    "confidence": 0,
    "category": "Regions",
    "broader": [
      3
    ],
    "narrower": [
      3,
      7
    ]
  },
  {
    "id": 6,
    "name": "Country Towns",
    "confidence": 1,
    "category": "Regions",
    "broader": [
      2,
      3
    ],
    "narrower": [
      7,
      14,
      37
    ]
  },
  {
    "id": 7,
    "name": "The Countryside",
    "confidence": 1,
    "category": "Regions",
    "broader": [
      2,
      3,
      4,
      5,
      6,
      14,
      26,
      115
    ],
    "narrower": [
      12,
      26
    ]
  },
  {
    "id": 8,
    "name": "Mosaic of Subcultures",
    "confidence": 2,
    "category": "Major City Structures",
    "broader": [
      3,
      4
    ],
    "narrower": [
      9,
      10,
      11,
      12,
      14,
      19,
      29
    ]
  },
  {
    "id": 9,
    "name": "Scattered Work",
    "confidence": 2,
    "category": "Major City Structures",
    "broader": [
      8
    ],
    "narrower": [
      12,
      13,
      14,
      19,
      37,
      42,
      59,
      157
    ]
  },
  {
    "id": 10,
    "name": "Magic of the City",
    "confidence": 0,
    "category": "Major City Structures",
    "broader": [
      3,
      8
    ],
    "narrower": [
      11,
      13,
      15,
      28,
      32,
      33,
      41,
      42,
      63,
      80,
      157
    ]
  },
  {
    "id": 11,
    "name": "Local Transport Areas",
    "confidence": 2,
    "category": "Major City Structures",
    "broader": [
      3,
      8,
      10,
      24
    ],
    "narrower": [
      16,
      17,
      19,
      22,
      23,
      31,
      33,
      34,
      49,
      56,
      58,
      63
    ]
  },
  {
    "id": 12,
    "name": "Community of 7000",
    "confidence": 1,
    "category": "Community Boundaries",
    "broader": [
      7,
      8,
      9
    ],
    "narrower": [
      14,
      15,
      22,
      26,
      27,
      28,
      29,
      30,
      33,
      44,
      62,
      65
    ]
  },
  {
    "id": 13,
    "name": "Subculture Boundary",
    "confidence": 0,
    "category": "Community Boundaries",
    "broader": [
      9,
      10,
      18
    ],
    "narrower": [
      15,
      19,
      23,
      28,
      29,
      30,
      42,
      48,
      60
    ]
  },
  {
    "id": 14,
    "name": "Identifiable Neighborhood",
    "confidence": 0,
    "category": "Community Boundaries",
    "broader": [
      6,
      8,
      9,
      12
    ],
    "narrower": [
      7,
      15,
      17,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      30,
      35,
      36,
      40,
      41,
      42,
      48,
      49,
      53,
      59,
      60,
      61,
      64,
      65,
      70,
      71,
      84,
      88,
      89,
      97
    ]
  },
  {
    "id": 15,
    "name": "Neighborhood Boundary",
    "confidence": 1,
    "category": "Community Boundaries",
    "broader": [
      10,
      12,
      13,
      14
    ],
    "narrower": [
      23,
      37,
      41,
      48,
      60,
      61,
      64,
      90
    ]
  },
  {
    "id": 16,
    "name": "Web of Public Transportation",
    "confidence": 0,
    "category": "Community Connections",
    "broader": [
      3,
      4,
      11
    ],
    "narrower": [
      17,
      34
    ]
  },
  {
    "id": 17,
    "name": "Ring Roads",
    "confidence": 0,
    "category": "Community Connections",
    "broader": [
      4,
      11,
      14,
      16,
      34,
      43
    ],
    "narrower": [
      20,
      23,
      34
    ]
  },
  {
    "id": 18,
    "name": "Network of Learning",
    "confidence": 1,
    "category": "Community Connections",
    "broader": [
      85
    ],
    "narrower": [
      13,
      25,
      42,
      43,
      57,
      85,
      157
    ]
  },
  {
    "id": 19,
    "name": "Web of Shopping",
    "confidence": 1,
    "category": "Community Connections",
    "broader": [
      8,
      9,
      11,
      13
    ],
    "narrower": [
      32,
      43,
      46,
      57,
      83,
      84,
      85,
      86
    ]
  },
  {
    "id": 20,
    "name": "Mini-Buses",
    "confidence": 0,
    "category": "Community Connections",
    "broader": [
      17
    ],
    "narrower": [
      92
    ]
  },
  {
    "id": 21,
    "name": "Four-Story Limit",
    "confidence": 0,
    "category": "Community Character",
    "broader": [],
    "narrower": [
      28,
      39,
      62,
      96
    ]
  },
  {
    "id": 22,
    "name": "Nine per Cent Parking",
    "confidence": 0,
    "category": "Community Character",
    "broader": [
      11,
      12,
      14
    ],
    "narrower": [
      29,
      39,
      62,
      82,
      95,
      96,
      97,
      103
    ]
  },
  {
    "id": 23,
    "name": "Parallel Roads",
    "confidence": 0,
    "category": "Community Character",
    "broader": [
      11,
      13,
      14,
      15,
      17,
      26,
      33,
      39
    ],
    "narrower": [
      49,
      50,
      52,
      54,
      55,
      57,
      97,
      103
    ]
  },
  {
    "id": 24,
    "name": "Sacred Sites",
    "confidence": 1,
    "category": "Community Character",
    "broader": [
      14,
      29
    ],
    "narrower": [
      11,
      25,
      49,
      50,
      51,
      52,
      54,
      55,
      64,
      66
    ]
  },
  {
    "id": 25,
    "name": "Access to Water",
    "confidence": 1,
    "category": "Community Character",
    "broader": [
      14,
      18,
      24
    ],
    "narrower": [
      59,
      64,
      66,
      71,
      134,
      171,
      176
    ]
  },
  {
    "id": 26,
    "name": "Life Cycle",
    "confidence": 1,
    "category": "Community Character",
    "broader": [
      7,
      12,
      14
    ],
    "narrower": [
      7,
      23,
      27,
      31,
      35,
      40,
      47,
      65,
      66,
      70,
      73,
      103
    ]
  },
  {
    "id": 27,
    "name": "Men and Women",
    "confidence": 0,
    "category": "Community Character",
    "broader": [
      12,
      14,
      26
    ],
    "narrower": [
      35,
      40,
      41,
      44,
      57,
      65,
      66,
      70,
      79,
      83,
      84,
      85,
      86,
      153,
      154,
      155,
      156,
      157,
      187
    ]
  },
  {
    "id": 28,
    "name": "Eccentric Nucleus",
    "confidence": 1,
    "category": "Local Centers",
    "broader": [
      10,
      12,
      13,
      14,
      21
    ],
    "narrower": [
      29,
      30
    ]
  },
  {
    "id": 29,
    "name": "Density Rings",
    "confidence": 1,
    "category": "Local Centers",
    "broader": [
      8,
      12,
      13,
      22,
      28
    ],
    "narrower": [
      24,
      30,
      31,
      32,
      36,
      38,
      39,
      59,
      71
    ]
  },
  {
    "id": 30,
    "name": "Activity Nodes",
    "confidence": 2,
    "category": "Local Centers",
    "broader": [
      12,
      13,
      14,
      28,
      29,
      31,
      32,
      34,
      45,
      52
    ],
    "narrower": [
      31,
      36,
      37,
      38,
      39,
      52,
      61,
      88,
      93,
      123
    ]
  },
  {
    "id": 31,
    "name": "Promenade",
    "confidence": 0,
    "category": "Local Centers",
    "broader": [
      11,
      26,
      29,
      30,
      44,
      65
    ],
    "narrower": [
      30,
      32,
      33,
      52,
      57,
      58,
      61,
      63,
      90,
      100,
      121,
      123,
      124
    ]
  },
  {
    "id": 32,
    "name": "Shopping Street",
    "confidence": 1,
    "category": "Local Centers",
    "broader": [
      10,
      19,
      29,
      31
    ],
    "narrower": [
      30,
      33,
      46,
      58,
      63,
      87,
      100,
      103,
      121,
      123
    ]
  },
  {
    "id": 33,
    "name": "Night Life",
    "confidence": 1,
    "category": "Local Centers",
    "broader": [
      10,
      11,
      12,
      31,
      32
    ],
    "narrower": [
      23,
      46,
      48,
      52,
      54,
      58,
      63,
      87,
      90,
      97,
      100,
      244
    ]
  },
  {
    "id": 34,
    "name": "Interchange",
    "confidence": 0,
    "category": "Local Centers",
    "broader": [
      11,
      16,
      17
    ],
    "narrower": [
      17,
      30,
      44,
      58,
      63,
      88,
      90,
      94,
      150
    ]
  },
  {
    "id": 35,
    "name": "Household Mix",
    "confidence": 1,
    "category": "House Clusters",
    "broader": [
      14,
      26,
      27,
      37,
      41
    ],
    "narrower": [
      40,
      73
    ]
  },
  {
    "id": 36,
    "name": "Degrees of Publicness",
    "confidence": 2,
    "category": "House Clusters",
    "broader": [
      14,
      29,
      30,
      38
    ],
    "narrower": [
      38,
      40,
      68,
      76,
      77,
      78,
      120
    ]
  },
  {
    "id": 37,
    "name": "House Cluster",
    "confidence": 0,
    "category": "House Clusters",
    "broader": [
      6,
      9,
      15,
      30,
      39,
      69
    ],
    "narrower": [
      35,
      38,
      48,
      49,
      53,
      67,
      71,
      73,
      76,
      77,
      103,
      157,
      175,
      178
    ]
  },
  {
    "id": 38,
    "name": "Row Houses",
    "confidence": 1,
    "category": "House Clusters",
    "broader": [
      29,
      30,
      36,
      37
    ],
    "narrower": [
      36,
      39,
      67,
      73,
      76,
      77,
      78,
      79,
      98,
      100,
      103,
      157
    ]
  },
  {
    "id": 39,
    "name": "Housing Hill",
    "confidence": 0,
    "category": "House Clusters",
    "broader": [
      21,
      22,
      29,
      30,
      38,
      98
    ],
    "narrower": [
      23,
      37,
      52,
      67,
      73,
      76,
      77,
      78,
      79,
      95,
      100,
      103,
      109
    ]
  },
  {
    "id": 40,
    "name": "Old People Everywhere",
    "confidence": 0,
    "category": "House Clusters",
    "broader": [
      14,
      26,
      27,
      35,
      36
    ],
    "narrower": [
      67,
      68,
      79,
      118,
      155,
      158,
      177
    ]
  },
  {
    "id": 41,
    "name": "Work Community",
    "confidence": 0,
    "category": "Work Communities",
    "broader": [
      10,
      14,
      15,
      27,
      43
    ],
    "narrower": [
      35,
      42,
      48,
      49,
      53,
      59,
      60,
      61,
      67,
      71,
      72,
      81,
      82,
      103,
      175
    ]
  },
  {
    "id": 42,
    "name": "Industrial Ribbon",
    "confidence": 1,
    "category": "Work Communities",
    "broader": [
      9,
      10,
      13,
      14,
      18,
      41
    ],
    "narrower": [
      60,
      61,
      72,
      80,
      88,
      93,
      100,
      115,
      147
    ]
  },
  {
    "id": 43,
    "name": "University As a Marketplace",
    "confidence": 0,
    "category": "Work Communities",
    "broader": [
      18,
      19
    ],
    "narrower": [
      17,
      41,
      45,
      81,
      100,
      106,
      122,
      151,
      165
    ]
  },
  {
    "id": 44,
    "name": "Local Town Hall",
    "confidence": 1,
    "category": "Work Communities",
    "broader": [
      12,
      27,
      34
    ],
    "narrower": [
      31,
      45,
      48,
      59,
      81,
      83,
      95,
      100,
      151,
      165
    ]
  },
  {
    "id": 45,
    "name": "Necklace of Community Projects",
    "confidence": 0,
    "category": "Work Communities",
    "broader": [
      43,
      44,
      47,
      82
    ],
    "narrower": [
      30,
      61,
      81,
      123,
      153,
      165
    ]
  },
  {
    "id": 46,
    "name": "Market of Many Shops",
    "confidence": 0,
    "category": "Work Communities",
    "broader": [
      19,
      32,
      33
    ],
    "narrower": [
      69,
      87,
      89,
      100,
      122,
      160,
      165
    ]
  },
  {
    "id": 47,
    "name": "Health Center",
    "confidence": 1,
    "category": "Work Communities",
    "broader": [
      26
    ],
    "narrower": [
      45,
      72,
      81,
      87,
      100,
      101,
      150,
      165,
      212,
      244
    ]
  },
  {
    "id": 48,
    "name": "Housing in Between",
    "confidence": 2,
    "category": "Work Communities",
    "broader": [
      13,
      14,
      15,
      33,
      37,
      41,
      44,
      98
    ],
    "narrower": [
      65,
      71,
      72,
      73,
      81,
      157,
      177
    ]
  },
  {
    "id": 49,
    "name": "Looped Local Roads",
    "confidence": 2,
    "category": "Roads and Paths",
    "broader": [
      11,
      14,
      23,
      24,
      37,
      41,
      115
    ],
    "narrower": [
      50,
      51,
      52,
      56,
      57
    ]
  },
  {
    "id": 50,
    "name": "T Junctions",
    "confidence": 1,
    "category": "Roads and Paths",
    "broader": [
      23,
      24,
      49
    ],
    "narrower": [
      51,
      52,
      103,
      113
    ]
  },
  {
    "id": 51,
    "name": "Green Streets",
    "confidence": 2,
    "category": "Roads and Paths",
    "broader": [
      24,
      49,
      50,
      53,
      67,
      68,
      69,
      115
    ],
    "narrower": [
      52,
      54,
      57,
      74,
      103,
      140,
      164,
      243,
      247
    ]
  },
  {
    "id": 52,
    "name": "Network of Paths and Cars",
    "confidence": 0,
    "category": "Roads and Paths",
    "broader": [
      23,
      24,
      30,
      31,
      33,
      39,
      49,
      50,
      51,
      120
    ],
    "narrower": [
      30,
      54,
      55,
      56,
      57,
      67,
      100,
      103,
      120,
      121,
      170,
      245,
      247
    ]
  },
  {
    "id": 53,
    "name": "Main Gateways",
    "confidence": 1,
    "category": "Roads and Paths",
    "broader": [
      14,
      37,
      41,
      93,
      95,
      98,
      99
    ],
    "narrower": [
      51,
      54,
      55,
      69,
      103,
      120,
      121
    ]
  },
  {
    "id": 54,
    "name": "Road Crossing",
    "confidence": 0,
    "category": "Roads and Paths",
    "broader": [
      23,
      24,
      33,
      51,
      52,
      53
    ],
    "narrower": [
      55,
      93,
      98,
      110,
      112
    ]
  },
  {
    "id": 55,
    "name": "Raised Walk",
    "confidence": 1,
    "category": "Roads and Paths",
    "broader": [
      23,
      24,
      52,
      53,
      54
    ],
    "narrower": [
      61,
      92,
      93,
      100,
      103,
      174,
      244
    ]
  },
  {
    "id": 56,
    "name": "Bike Paths and Racks",
    "confidence": 1,
    "category": "Roads and Paths",
    "broader": [
      11,
      49,
      52,
      74
    ],
    "narrower": [
      57,
      119,
      125,
      243
    ]
  },
  {
    "id": 57,
    "name": "Children in the City",
    "confidence": 0,
    "category": "Roads and Paths",
    "broader": [
      18,
      19,
      23,
      27,
      31,
      49,
      51,
      52,
      56
    ],
    "narrower": [
      110,
      119,
      173
    ]
  },
  {
    "id": 58,
    "name": "Carnival",
    "confidence": 0,
    "category": "Common Land",
    "broader": [
      11,
      31,
      32,
      33,
      34
    ],
    "narrower": [
      63
    ]
  },
  {
    "id": 59,
    "name": "Quiet Backs",
    "confidence": 1,
    "category": "Common Land",
    "broader": [
      9,
      14,
      25,
      29,
      41,
      44,
      71
    ],
    "narrower": [
      60,
      61,
      63,
      64,
      69,
      93,
      100,
      173,
      244
    ]
  },
  {
    "id": 60,
    "name": "Accessible Green",
    "confidence": 2,
    "category": "Common Land",
    "broader": [
      13,
      14,
      15,
      41,
      42,
      59,
      115
    ],
    "narrower": [
      64,
      67,
      69,
      71,
      171,
      173
    ]
  },
  {
    "id": 61,
    "name": "Small Public Squares",
    "confidence": 2,
    "category": "Common Land",
    "broader": [
      14,
      15,
      30,
      31,
      41,
      42,
      45,
      55,
      59,
      63,
      115
    ],
    "narrower": [
      62,
      63,
      66,
      69,
      70,
      72,
      74,
      88,
      93,
      94,
      123,
      124,
      125,
      126,
      164
    ]
  },
  {
    "id": 62,
    "name": "High Places",
    "confidence": 1,
    "category": "Common Land",
    "broader": [
      12,
      21,
      22,
      61,
      66
    ],
    "narrower": [
      106,
      114,
      122,
      123,
      124,
      125,
      126
    ]
  },
  {
    "id": 63,
    "name": "Dancing in the Street",
    "confidence": 1,
    "category": "Common Land",
    "broader": [
      10,
      11,
      31,
      32,
      33,
      34,
      58,
      59,
      61
    ],
    "narrower": [
      61,
      125,
      134,
      158
    ]
  },
  {
    "id": 64,
    "name": "Pools and Streams",
    "confidence": 1,
    "category": "Common Land",
    "broader": [
      14,
      15,
      24,
      25,
      59,
      60,
      72,
      100
    ],
    "narrower": [
      69,
      71,
      93,
      124,
      244
    ]
  },
  {
    "id": 65,
    "name": "Birth Places",
    "confidence": 0,
    "category": "Common Land",
    "broader": [
      12,
      14,
      26,
      27,
      48,
      92
    ],
    "narrower": [
      31,
      66,
      71,
      121,
      179
    ]
  },
  {
    "id": 66,
    "name": "Holy Ground",
    "confidence": 1,
    "category": "Common Land",
    "broader": [
      24,
      25,
      26,
      27,
      61,
      65
    ],
    "narrower": [
      62,
      70,
      95,
      111,
      129,
      136,
      139,
      173
    ]
  },
  {
    "id": 67,
    "name": "Common Land",
    "confidence": 2,
    "category": "Local Common Land",
    "broader": [
      37,
      38,
      39,
      40,
      41,
      52,
      60,
      99,
      115
    ],
    "narrower": [
      51,
      68,
      69,
      70,
      71,
      73,
      74,
      126,
      170,
      175,
      177
    ]
  },
  {
    "id": 68,
    "name": "Connected Play",
    "confidence": 1,
    "category": "Local Common Land",
    "broader": [
      36,
      40,
      67
    ],
    "narrower": [
      51,
      69,
      72,
      73,
      105,
      106,
      114,
      177
    ]
  },
  {
    "id": 69,
    "name": "Public Outdoor Room",
    "confidence": 2,
    "category": "Local Common Land",
    "broader": [
      46,
      53,
      59,
      60,
      61,
      64,
      67,
      68,
      72,
      93,
      100,
      111,
      120,
      122,
      129,
      139,
      140,
      142,
      161
    ],
    "narrower": [
      37,
      51,
      71,
      73,
      74,
      86,
      94,
      113,
      124,
      128,
      145,
      159,
      173,
      178,
      198,
      226
    ]
  },
  {
    "id": 70,
    "name": "Grave Sites",
    "confidence": 1,
    "category": "Local Common Land",
    "broader": [
      14,
      26,
      27,
      61,
      66,
      67
    ],
    "narrower": [
      115,
      119,
      121,
      124,
      125,
      129,
      160,
      163,
      241,
      244
    ]
  },
  {
    "id": 71,
    "name": "Still Water",
    "confidence": 1,
    "category": "Local Common Land",
    "broader": [
      14,
      25,
      29,
      37,
      41,
      48,
      60,
      64,
      65,
      67,
      69,
      72,
      73,
      145,
      151,
      173
    ],
    "narrower": [
      59,
      171,
      241
    ]
  },
  {
    "id": 72,
    "name": "Local Sports",
    "confidence": 1,
    "category": "Local Common Land",
    "broader": [
      41,
      42,
      47,
      48,
      61,
      68,
      85
    ],
    "narrower": [
      64,
      69,
      71,
      105,
      174,
      243
    ]
  },
  {
    "id": 73,
    "name": "Adventure Playground",
    "confidence": 0,
    "category": "Local Common Land",
    "broader": [
      26,
      35,
      37,
      38,
      39,
      48,
      67,
      68,
      69
    ],
    "narrower": [
      71,
      95,
      101,
      144,
      165,
      203,
      241,
      243
    ]
  },
  {
    "id": 74,
    "name": "Animals",
    "confidence": 0,
    "category": "Local Common Land",
    "broader": [
      51,
      61,
      67,
      69,
      79
    ],
    "narrower": [
      56,
      161,
      172,
      173,
      178,
      203,
      243
    ]
  },
  {
    "id": 75,
    "name": "The Family",
    "confidence": 1,
    "category": "Local Common Land",
    "broader": [],
    "narrower": []
  },
  {
    "id": 76,
    "name": "House for a Small Family",
    "confidence": 0,
    "category": "The Family",
    "broader": [
      36,
      37,
      38,
      39
    ],
    "narrower": [
      77,
      78,
      79,
      95,
      107,
      129,
      145,
      147,
      158
    ]
  },
  {
    "id": 77,
    "name": "House for a Couple",
    "confidence": 1,
    "category": "The Family",
    "broader": [
      36,
      37,
      38,
      39,
      76
    ],
    "narrower": [
      78,
      79,
      107,
      129,
      136,
      137,
      143,
      158
    ]
  },
  {
    "id": 78,
    "name": "House for One Person",
    "confidence": 1,
    "category": "The Family",
    "broader": [
      36,
      38,
      39,
      76,
      77,
      156
    ],
    "narrower": [
      79,
      107,
      136,
      158
    ]
  },
  {
    "id": 79,
    "name": "Your Own Home",
    "confidence": 0,
    "category": "The Family",
    "broader": [
      27,
      38,
      39,
      40,
      76,
      77,
      78
    ],
    "narrower": [
      74,
      139,
      144,
      154,
      155,
      157,
      180,
      183,
      188,
      189
    ]
  },
  {
    "id": 80,
    "name": "Self-Governing Workshops and Offices",
    "confidence": 0,
    "category": "Work Groups",
    "broader": [
      10,
      42
    ],
    "narrower": [
      82,
      107,
      145,
      146,
      147,
      148,
      149,
      153,
      158
    ]
  },
  {
    "id": 81,
    "name": "Small Services Without Red Tape",
    "confidence": 0,
    "category": "Work Groups",
    "broader": [
      41,
      43,
      44,
      45,
      47,
      48,
      84
    ],
    "narrower": [
      82,
      83,
      95,
      107,
      148,
      149,
      150,
      153,
      158
    ]
  },
  {
    "id": 82,
    "name": "Office Connections",
    "confidence": 1,
    "category": "Work Groups",
    "broader": [
      22,
      41,
      80,
      81,
      149
    ],
    "narrower": [
      45,
      95,
      101,
      102,
      107,
      146,
      148,
      150
    ]
  },
  {
    "id": 83,
    "name": "Master and Apprentices",
    "confidence": 0,
    "category": "Work Groups",
    "broader": [
      19,
      27,
      44,
      81,
      149
    ],
    "narrower": [
      107,
      151
    ]
  },
  {
    "id": 84,
    "name": "Teenage Society",
    "confidence": 0,
    "category": "Work Groups",
    "broader": [
      14,
      19,
      27
    ],
    "narrower": [
      81
    ]
  },
  {
    "id": 85,
    "name": "Shopfront Schools",
    "confidence": 0,
    "category": "Work Groups",
    "broader": [
      18,
      19,
      27,
      86
    ],
    "narrower": [
      18,
      72,
      95,
      147,
      157
    ]
  },
  {
    "id": 86,
    "name": "Children's Home",
    "confidence": 0,
    "category": "Work Groups",
    "broader": [
      19,
      27,
      69
    ],
    "narrower": [
      85,
      203
    ]
  },
  {
    "id": 87,
    "name": "Individually Owned Shops",
    "confidence": 0,
    "category": "Local Shops",
    "broader": [
      32,
      33,
      46,
      47,
      88,
      89,
      90,
      94,
      98
    ],
    "narrower": [
      107,
      145
    ]
  },
  {
    "id": 88,
    "name": "Street Cafe",
    "confidence": 2,
    "category": "Local Shops",
    "broader": [
      14,
      30,
      34,
      42,
      61,
      124,
      125,
      151
    ],
    "narrower": [
      87,
      94,
      95,
      165,
      191,
      197,
      200
    ]
  },
  {
    "id": 89,
    "name": "Corner Grocery",
    "confidence": 1,
    "category": "Local Shops",
    "broader": [
      14,
      46
    ],
    "narrower": [
      87,
      95,
      125,
      150,
      165,
      243,
      244,
      251
    ]
  },
  {
    "id": 90,
    "name": "Beer Hall",
    "confidence": 0,
    "category": "Local Shops",
    "broader": [
      15,
      31,
      33,
      34,
      92
    ],
    "narrower": [
      87,
      95,
      110,
      165,
      191,
      197,
      200
    ]
  },
  {
    "id": 91,
    "name": "Traveler's Inn",
    "confidence": 0,
    "category": "Local Shops",
    "broader": [],
    "narrower": [
      149
    ]
  },
  {
    "id": 92,
    "name": "Bus Stop",
    "confidence": 1,
    "category": "Local Shops",
    "broader": [
      20,
      55,
      125
    ],
    "narrower": [
      65,
      90,
      93,
      94,
      95,
      129,
      147,
      186
    ]
  },
  {
    "id": 93,
    "name": "Food Stands",
    "confidence": 1,
    "category": "Local Shops",
    "broader": [
      30,
      42,
      54,
      55,
      59,
      61,
      64,
      92,
      125
    ],
    "narrower": [
      53,
      69,
      125,
      150
    ]
  },
  {
    "id": 94,
    "name": "Sleeping in Public",
    "confidence": 0,
    "category": "Local Shops",
    "broader": [
      34,
      61,
      69,
      88,
      92,
      100,
      101,
      150,
      151
    ],
    "narrower": [
      87,
      124,
      244
    ]
  },
  {
    "id": 95,
    "name": "Building Complex",
    "confidence": 2,
    "category": "Building Arrangement",
    "broader": [
      22,
      39,
      44,
      66,
      73,
      76,
      81,
      82,
      85,
      88,
      89,
      90,
      92
    ],
    "narrower": [
      53,
      96,
      97,
      99,
      100,
      101,
      104,
      116,
      120,
      122,
      145
    ]
  },
  {
    "id": 96,
    "name": "Number of Stories",
    "confidence": 1,
    "category": "Building Arrangement",
    "broader": [
      21,
      22,
      95
    ],
    "narrower": [
      98,
      99,
      104,
      105,
      107,
      116,
      205
    ]
  },
  {
    "id": 97,
    "name": "Shielded Parking",
    "confidence": 1,
    "category": "Building Arrangement",
    "broader": [
      14,
      22,
      23,
      33,
      95
    ],
    "narrower": [
      103,
      205,
      213
    ]
  },
  {
    "id": 98,
    "name": "Circulation Realms",
    "confidence": 2,
    "category": "Building Arrangement",
    "broader": [
      38,
      54,
      96
    ],
    "narrower": [
      39,
      48,
      53,
      87,
      99,
      100,
      101,
      102,
      103,
      104,
      110,
      119,
      120,
      132,
      135,
      158,
      166,
      205,
      244
    ]
  },
  {
    "id": 99,
    "name": "Main Building",
    "confidence": 1,
    "category": "Building Arrangement",
    "broader": [
      95,
      96,
      98
    ],
    "narrower": [
      53,
      67,
      100,
      101,
      102,
      110,
      114,
      115,
      120
    ]
  },
  {
    "id": 100,
    "name": "Pedestrian Street",
    "confidence": 2,
    "category": "Building Arrangement",
    "broader": [
      31,
      32,
      33,
      38,
      39,
      42,
      43,
      44,
      46,
      47,
      52,
      55,
      59,
      95,
      98,
      99,
      102
    ],
    "narrower": [
      64,
      69,
      94,
      101,
      116,
      119,
      121,
      123,
      124,
      129,
      140,
      158,
      164,
      166,
      205,
      243
    ]
  },
  {
    "id": 101,
    "name": "Building Thoroughfare",
    "confidence": 0,
    "category": "Building Arrangement",
    "broader": [
      47,
      73,
      82,
      95,
      98,
      99,
      100
    ],
    "narrower": [
      94,
      102,
      119,
      121,
      123,
      132,
      140,
      158,
      164,
      165,
      166,
      167,
      194
    ]
  },
  {
    "id": 102,
    "name": "Family of Entrances",
    "confidence": 1,
    "category": "Building Arrangement",
    "broader": [
      82,
      98,
      99,
      101,
      121,
      131
    ],
    "narrower": [
      100,
      112,
      123,
      124,
      125,
      130,
      135,
      149,
      158,
      180,
      190,
      194,
      224,
      237
    ]
  },
  {
    "id": 103,
    "name": "Small Parking Lots",
    "confidence": 1,
    "category": "Building Arrangement",
    "broader": [
      22,
      23,
      26,
      32,
      37,
      38,
      39,
      41,
      50,
      51,
      52,
      53,
      55,
      97,
      98
    ],
    "narrower": [
      110,
      112,
      130,
      149,
      244
    ]
  },
  {
    "id": 104,
    "name": "Site Repair",
    "confidence": 2,
    "category": "Building Location",
    "broader": [
      95,
      96,
      98
    ],
    "narrower": [
      105,
      114,
      169,
      171,
      214
    ]
  },
  {
    "id": 105,
    "name": "South Facing Outdoors",
    "confidence": 0,
    "category": "Building Location",
    "broader": [
      68,
      72,
      96,
      104
    ],
    "narrower": [
      106,
      107,
      109,
      114,
      128,
      161,
      162,
      169,
      171,
      172
    ]
  },
  {
    "id": 106,
    "name": "Positive Outdoor Space",
    "confidence": 0,
    "category": "Building Location",
    "broader": [
      43,
      62,
      68,
      105,
      107,
      115,
      174,
      192
    ],
    "narrower": [
      107,
      109,
      111,
      114,
      115,
      120,
      122,
      125,
      128,
      159,
      160,
      161,
      162,
      174,
      243
    ]
  },
  {
    "id": 107,
    "name": "Wings of Light",
    "confidence": 2,
    "category": "Building Location",
    "broader": [
      76,
      77,
      78,
      80,
      81,
      82,
      83,
      87,
      96,
      105,
      106
    ],
    "narrower": [
      106,
      114,
      115,
      116,
      117,
      118,
      120,
      121,
      122,
      159,
      160,
      163,
      172
    ]
  },
  {
    "id": 108,
    "name": "Connected Buildings",
    "confidence": 1,
    "category": "Building Location",
    "broader": [],
    "narrower": [
      115,
      119,
      163
    ]
  },
  {
    "id": 109,
    "name": "Long Thin House",
    "confidence": 1,
    "category": "Building Location",
    "broader": [
      39,
      105,
      106
    ],
    "narrower": [
      159
    ]
  },
  {
    "id": 110,
    "name": "Main Entrance",
    "confidence": 0,
    "category": "Building Shape",
    "broader": [
      54,
      57,
      90,
      98,
      99,
      103,
      112,
      121,
      243
    ],
    "narrower": [
      112,
      113,
      125,
      130,
      133,
      224,
      249
    ]
  },
  {
    "id": 111,
    "name": "Half-Hidden Garden",
    "confidence": 0,
    "category": "Building Shape",
    "broader": [
      66,
      106
    ],
    "narrower": [
      69,
      112,
      140,
      170,
      173
    ]
  },
  {
    "id": 112,
    "name": "Entrance Transition",
    "confidence": 2,
    "category": "Building Shape",
    "broader": [
      54,
      102,
      103,
      110,
      111,
      114
    ],
    "narrower": [
      110,
      113,
      115,
      118,
      130,
      134,
      140,
      172,
      173,
      174
    ]
  },
  {
    "id": 113,
    "name": "Car Connection",
    "confidence": 0,
    "category": "Building Shape",
    "broader": [
      50,
      69,
      110,
      112
    ],
    "narrower": [
      127,
      130,
      134,
      135,
      173,
      174
    ]
  },
  {
    "id": 114,
    "name": "Hierarchy of Open Space",
    "confidence": 0,
    "category": "Building Shape",
    "broader": [
      62,
      68,
      99,
      104,
      105,
      106,
      107,
      116,
      174
    ],
    "narrower": [
      112,
      115,
      119,
      120,
      127,
      129,
      162,
      163,
      205,
      243,
      245
    ]
  },
  {
    "id": 115,
    "name": "Courtyards Which Live",
    "confidence": 0,
    "category": "Building Shape",
    "broader": [
      42,
      70,
      99,
      106,
      107,
      108,
      112,
      114
    ],
    "narrower": [
      7,
      49,
      51,
      60,
      61,
      67,
      106,
      124,
      126,
      140,
      176
    ]
  },
  {
    "id": 116,
    "name": "Cascade of Roofs",
    "confidence": 1,
    "category": "Building Shape",
    "broader": [
      95,
      96,
      100,
      107
    ],
    "narrower": [
      114,
      117,
      118,
      119,
      126,
      129,
      134,
      159,
      161,
      163,
      166,
      167,
      173,
      201,
      209
    ]
  },
  {
    "id": 117,
    "name": "Sheltering Roof",
    "confidence": 2,
    "category": "Building Shape",
    "broader": [
      107,
      116,
      120
    ],
    "narrower": [
      118,
      190,
      205,
      209,
      220,
      231
    ]
  },
  {
    "id": 118,
    "name": "Roof Garden",
    "confidence": 1,
    "category": "Building Shape",
    "broader": [
      40,
      107,
      112,
      116,
      117
    ],
    "narrower": [
      119,
      145,
      166,
      209,
      220,
      231,
      232,
      244
    ]
  },
  {
    "id": 119,
    "name": "Arcades",
    "confidence": 2,
    "category": "Paths",
    "broader": [
      56,
      57,
      70,
      98,
      100,
      101,
      108,
      114,
      116,
      118,
      122,
      125,
      130,
      161
    ],
    "narrower": [
      120,
      122,
      166,
      168,
      226,
      227,
      242,
      244
    ]
  },
  {
    "id": 120,
    "name": "Paths and Goals",
    "confidence": 1,
    "category": "Paths",
    "broader": [
      36,
      52,
      53,
      95,
      98,
      99,
      106,
      107,
      114,
      119,
      125,
      171
    ],
    "narrower": [
      52,
      69,
      117,
      121,
      134,
      160,
      174,
      190,
      193,
      205,
      224,
      226,
      227,
      245
    ]
  },
  {
    "id": 121,
    "name": "Path Shape",
    "confidence": 1,
    "category": "Paths",
    "broader": [
      31,
      32,
      52,
      53,
      65,
      70,
      100,
      101,
      107,
      120,
      166
    ],
    "narrower": [
      102,
      110,
      122,
      123,
      124,
      125,
      126,
      171,
      241,
      243,
      245,
      247
    ]
  },
  {
    "id": 122,
    "name": "Building Fronts",
    "confidence": 1,
    "category": "Paths",
    "broader": [
      43,
      46,
      62,
      95,
      106,
      107,
      119,
      121,
      124,
      125
    ],
    "narrower": [
      69,
      119,
      123,
      124,
      125,
      164
    ]
  },
  {
    "id": 123,
    "name": "Pedestrian Density",
    "confidence": 1,
    "category": "Paths",
    "broader": [
      30,
      31,
      32,
      45,
      61,
      62,
      100,
      101,
      102,
      121,
      122
    ],
    "narrower": [
      125,
      140,
      158,
      160,
      164,
      165,
      166,
      242
    ]
  },
  {
    "id": 124,
    "name": "Activity Pockets",
    "confidence": 2,
    "category": "Paths",
    "broader": [
      31,
      61,
      62,
      64,
      69,
      70,
      94,
      100,
      102,
      115,
      121,
      122
    ],
    "narrower": [
      88,
      122,
      125,
      126,
      140,
      160,
      164,
      165,
      166,
      241,
      243
    ]
  },
  {
    "id": 125,
    "name": "Stair Seats",
    "confidence": 1,
    "category": "Paths",
    "broader": [
      56,
      61,
      62,
      63,
      70,
      89,
      93,
      102,
      106,
      110,
      121,
      122,
      123,
      124,
      134,
      158,
      161,
      196,
      242
    ],
    "narrower": [
      88,
      92,
      93,
      119,
      120,
      122,
      126,
      150,
      163,
      174,
      241,
      243,
      245
    ]
  },
  {
    "id": 126,
    "name": "Something Roughly in the Middle",
    "confidence": 0,
    "category": "Paths",
    "broader": [
      61,
      62,
      67,
      115,
      116,
      121,
      124,
      125
    ],
    "narrower": [
      168,
      241,
      248
    ]
  },
  {
    "id": 127,
    "name": "Intimacy Gradient",
    "confidence": 0,
    "category": "Gradients of Space",
    "broader": [
      113,
      114
    ],
    "narrower": [
      128,
      129,
      131,
      138,
      142,
      144,
      146,
      185,
      233
    ]
  },
  {
    "id": 128,
    "name": "Indoor Sunlight",
    "confidence": 1,
    "category": "Gradients of Space",
    "broader": [
      69,
      105,
      106,
      127
    ],
    "narrower": [
      129,
      130,
      138,
      141,
      142,
      144,
      149,
      152,
      162,
      199
    ]
  },
  {
    "id": 129,
    "name": "Common Areas at the Heart",
    "confidence": 0,
    "category": "Gradients of Space",
    "broader": [
      66,
      70,
      76,
      77,
      92,
      100,
      114,
      116,
      127,
      128,
      143,
      149,
      186
    ],
    "narrower": [
      69,
      131,
      138,
      140,
      144,
      146,
      147,
      157,
      161,
      162,
      163,
      179,
      181,
      183,
      199,
      236,
      252
    ]
  },
  {
    "id": 130,
    "name": "Entrance Room",
    "confidence": 2,
    "category": "Gradients of Space",
    "broader": [
      102,
      103,
      110,
      112,
      113,
      128,
      132,
      140,
      143
    ],
    "narrower": [
      119,
      131,
      132,
      134,
      139,
      142,
      147,
      149,
      159,
      163,
      180,
      181,
      191,
      194,
      242,
      252
    ]
  },
  {
    "id": 131,
    "name": "The Flow Through Rooms",
    "confidence": 0,
    "category": "Gradients of Space",
    "broader": [
      127,
      129,
      130
    ],
    "narrower": [
      102,
      132,
      133,
      135,
      142,
      159,
      166,
      194,
      196,
      201,
      202,
      224,
      237,
      242
    ]
  },
  {
    "id": 132,
    "name": "Short Passages",
    "confidence": 1,
    "category": "Gradients of Space",
    "broader": [
      98,
      101,
      130,
      131,
      138
    ],
    "narrower": [
      130,
      133,
      134,
      135,
      159,
      194,
      196
    ]
  },
  {
    "id": 133,
    "name": "Staircase As a Stage",
    "confidence": 0,
    "category": "Gradients of Space",
    "broader": [
      110,
      131,
      132
    ],
    "narrower": [
      134,
      135,
      159,
      163,
      166,
      179,
      180,
      194,
      197,
      198,
      222,
      228,
      237
    ]
  },
  {
    "id": 134,
    "name": "Zen View",
    "confidence": 1,
    "category": "Gradients of Space",
    "broader": [
      25,
      63,
      112,
      113,
      116,
      120,
      130,
      132,
      133,
      143,
      174
    ],
    "narrower": [
      125,
      135,
      180,
      191,
      195,
      221,
      222
    ]
  },
  {
    "id": 135,
    "name": "Tapestry of Light and Dark",
    "confidence": 0,
    "category": "Gradients of Space",
    "broader": [
      98,
      102,
      113,
      131,
      132,
      133,
      134,
      150
    ],
    "narrower": [
      180,
      194,
      196,
      221,
      237
    ]
  },
  {
    "id": 136,
    "name": "Couple's Realm",
    "confidence": 0,
    "category": "House Rooms",
    "broader": [
      66,
      77,
      78,
      143
    ],
    "narrower": [
      138,
      143,
      144,
      186,
      187
    ]
  },
  {
    "id": 137,
    "name": "Children's Realm",
    "confidence": 0,
    "category": "House Rooms",
    "broader": [
      77,
      144
    ],
    "narrower": [
      138,
      143,
      144,
      186,
      203
    ]
  },
  {
    "id": 138,
    "name": "Sleeping to the East",
    "confidence": 1,
    "category": "House Rooms",
    "broader": [
      127,
      128,
      129,
      136,
      137
    ],
    "narrower": [
      132,
      139,
      143,
      144,
      157,
      163,
      186
    ]
  },
  {
    "id": 139,
    "name": "Farmhouse Kitchen",
    "confidence": 0,
    "category": "House Rooms",
    "broader": [
      66,
      79,
      130,
      138,
      143,
      148
    ],
    "narrower": [
      69,
      179,
      182,
      184,
      199,
      200
    ]
  },
  {
    "id": 140,
    "name": "Private Terrace on the Street",
    "confidence": 0,
    "category": "House Rooms",
    "broader": [
      51,
      100,
      101,
      111,
      112,
      115,
      123,
      124,
      129,
      142,
      143,
      156,
      157,
      162,
      174
    ],
    "narrower": [
      69,
      130,
      142,
      159,
      168,
      173,
      179,
      182,
      184,
      199,
      200,
      201,
      241,
      243,
      244,
      247
    ]
  },
  {
    "id": 141,
    "name": "A Room of One's Own",
    "confidence": 0,
    "category": "House Rooms",
    "broader": [
      128,
      143
    ],
    "narrower": [
      156,
      188
    ]
  },
  {
    "id": 142,
    "name": "Sequence of Sitting Spaces",
    "confidence": 0,
    "category": "House Rooms",
    "broader": [
      127,
      128,
      130,
      131,
      140,
      186
    ],
    "narrower": [
      69,
      140,
      154,
      155,
      157,
      159,
      179,
      183,
      185,
      188,
      189,
      191,
      194,
      196,
      251,
      253
    ]
  },
  {
    "id": 143,
    "name": "Bed Cluster",
    "confidence": 1,
    "category": "House Rooms",
    "broader": [
      77,
      136,
      137,
      138,
      187
    ],
    "narrower": [
      129,
      130,
      134,
      136,
      139,
      140,
      141,
      144,
      146,
      150,
      152,
      180,
      181,
      185,
      186,
      188,
      191,
      241
    ]
  },
  {
    "id": 144,
    "name": "Bathing Room",
    "confidence": 1,
    "category": "House Rooms",
    "broader": [
      73,
      79,
      127,
      128,
      129,
      136,
      137,
      138,
      143,
      178
    ],
    "narrower": [
      137,
      159,
      186,
      188,
      189,
      191,
      198,
      203
    ]
  },
  {
    "id": 145,
    "name": "Bulk Storage",
    "confidence": 0,
    "category": "House Rooms",
    "broader": [
      69,
      76,
      80,
      87,
      95,
      118,
      191
    ],
    "narrower": [
      71,
      159,
      173,
      178,
      238
    ]
  },
  {
    "id": 146,
    "name": "Flexible Office Space",
    "confidence": 0,
    "category": "Work Rooms",
    "broader": [
      80,
      82,
      127,
      129,
      143,
      149
    ],
    "narrower": [
      148,
      149,
      151,
      153,
      179,
      183,
      252
    ]
  },
  {
    "id": 147,
    "name": "Communal Eating",
    "confidence": 1,
    "category": "Work Rooms",
    "broader": [
      42,
      76,
      80,
      85,
      92,
      129,
      130
    ],
    "narrower": [
      148,
      149,
      152,
      182
    ]
  },
  {
    "id": 148,
    "name": "Small Work Groups",
    "confidence": 2,
    "category": "Work Rooms",
    "broader": [
      80,
      81,
      82,
      146,
      147
    ],
    "narrower": [
      139,
      151,
      158,
      182
    ]
  },
  {
    "id": 149,
    "name": "Reception Welcomes You",
    "confidence": 0,
    "category": "Work Rooms",
    "broader": [
      80,
      81,
      91,
      102,
      103,
      128,
      130,
      146,
      147
    ],
    "narrower": [
      82,
      83,
      129,
      146,
      152,
      158,
      183
    ]
  },
  {
    "id": 150,
    "name": "A Place to Wait",
    "confidence": 1,
    "category": "Work Rooms",
    "broader": [
      34,
      47,
      81,
      82,
      89,
      93,
      125,
      143
    ],
    "narrower": [
      94,
      135,
      159,
      179,
      180,
      181,
      183,
      191
    ]
  },
  {
    "id": 151,
    "name": "Small Meeting Rooms",
    "confidence": 1,
    "category": "Work Rooms",
    "broader": [
      43,
      44,
      83,
      146,
      148
    ],
    "narrower": [
      71,
      88,
      94,
      164,
      165,
      176,
      179,
      180,
      191
    ]
  },
  {
    "id": 152,
    "name": "Half-Private Office",
    "confidence": 0,
    "category": "Work Rooms",
    "broader": [
      128,
      143,
      147,
      149
    ],
    "narrower": [
      183
    ]
  },
  {
    "id": 153,
    "name": "Rooms to Rent",
    "confidence": 0,
    "category": "Outbuildings",
    "broader": [
      27,
      45,
      80,
      81,
      146,
      154,
      155,
      157
    ],
    "narrower": [
      155,
      158
    ]
  },
  {
    "id": 154,
    "name": "Teenager's Cottage",
    "confidence": 0,
    "category": "Outbuildings",
    "broader": [
      27,
      79,
      142
    ],
    "narrower": [
      153,
      155,
      158
    ]
  },
  {
    "id": 155,
    "name": "Old Age Cottage",
    "confidence": 2,
    "category": "Outbuildings",
    "broader": [
      27,
      40,
      79,
      142,
      153,
      154
    ],
    "narrower": [
      153,
      156,
      157,
      158,
      185,
      188,
      191,
      205,
      242
    ]
  },
  {
    "id": 156,
    "name": "Settled Work",
    "confidence": 1,
    "category": "Outbuildings",
    "broader": [
      27,
      141,
      155
    ],
    "narrower": [
      78,
      140,
      158,
      164,
      191,
      205,
      242
    ]
  },
  {
    "id": 157,
    "name": "Home Workshop",
    "confidence": 0,
    "category": "Outbuildings",
    "broader": [
      9,
      10,
      18,
      27,
      37,
      38,
      48,
      79,
      85,
      129,
      138,
      142,
      155
    ],
    "narrower": [
      140,
      153,
      158,
      165,
      183
    ]
  },
  {
    "id": 158,
    "name": "Open Stairs",
    "confidence": 1,
    "category": "Outbuildings",
    "broader": [
      40,
      63,
      76,
      77,
      78,
      80,
      81,
      98,
      100,
      101,
      102,
      123,
      148,
      149,
      153,
      154,
      155,
      156,
      157
    ],
    "narrower": [
      125,
      159,
      161,
      165,
      183,
      191,
      192
    ]
  },
  {
    "id": 159,
    "name": "Light on Two Sides of Every Room",
    "confidence": 0,
    "category": "Room Edges",
    "broader": [
      69,
      106,
      107,
      109,
      116,
      130,
      131,
      132,
      133,
      140,
      142,
      144,
      145,
      150,
      158
    ],
    "narrower": [
      160,
      180,
      192,
      223
    ]
  },
  {
    "id": 160,
    "name": "Building Edge",
    "confidence": 2,
    "category": "Room Edges",
    "broader": [
      46,
      70,
      106,
      107,
      120,
      123,
      124,
      159
    ],
    "narrower": [
      161,
      166,
      168,
      169,
      180,
      192,
      221,
      223,
      238,
      241,
      245,
      249
    ]
  },
  {
    "id": 161,
    "name": "Sunny Place",
    "confidence": 2,
    "category": "Room Edges",
    "broader": [
      74,
      105,
      106,
      116,
      129,
      158,
      160,
      163,
      168
    ],
    "narrower": [
      69,
      119,
      125,
      162,
      163,
      164,
      166,
      167,
      168,
      176,
      241,
      242
    ]
  },
  {
    "id": 162,
    "name": "North Face",
    "confidence": 0,
    "category": "Room Edges",
    "broader": [
      105,
      106,
      114,
      128,
      129,
      161
    ],
    "narrower": [
      140,
      163,
      167,
      174,
      238,
      241,
      244
    ]
  },
  {
    "id": 163,
    "name": "Outdoor Room",
    "confidence": 0,
    "category": "Room Edges",
    "broader": [
      70,
      107,
      108,
      114,
      116,
      125,
      129,
      130,
      133,
      138,
      161,
      162,
      166,
      168,
      172
    ],
    "narrower": [
      161,
      174,
      226,
      241,
      243,
      244,
      247
    ]
  },
  {
    "id": 164,
    "name": "Street Windows",
    "confidence": 1,
    "category": "Room Edges",
    "broader": [
      51,
      61,
      100,
      101,
      122,
      123,
      124,
      151,
      156,
      161
    ],
    "narrower": [
      165,
      168,
      173,
      174,
      180,
      191,
      205,
      221,
      226,
      243,
      244
    ]
  },
  {
    "id": 165,
    "name": "Opening to the Street",
    "confidence": 1,
    "category": "Room Edges",
    "broader": [
      43,
      44,
      45,
      46,
      47,
      73,
      88,
      89,
      90,
      101,
      123,
      124,
      151,
      157,
      158,
      164
    ],
    "narrower": [
      180,
      236,
      238,
      243,
      246
    ]
  },
  {
    "id": 166,
    "name": "Gallery Surround",
    "confidence": 1,
    "category": "Room Edges",
    "broader": [
      98,
      100,
      101,
      116,
      118,
      119,
      123,
      124,
      131,
      133,
      160,
      161
    ],
    "narrower": [
      121,
      163,
      168,
      226,
      227,
      243,
      244
    ]
  },
  {
    "id": 167,
    "name": "Six-Foot Balcony",
    "confidence": 0,
    "category": "Room Edges",
    "broader": [
      101,
      116,
      161,
      162
    ],
    "narrower": [
      168,
      226,
      227
    ]
  },
  {
    "id": 168,
    "name": "Connection to the Earth",
    "confidence": 0,
    "category": "Room Edges",
    "broader": [
      119,
      126,
      140,
      160,
      161,
      164,
      166,
      167,
      216,
      248
    ],
    "narrower": [
      161,
      163,
      169,
      191,
      193,
      214,
      215,
      226,
      241,
      242,
      243,
      247,
      248,
      249
    ]
  },
  {
    "id": 169,
    "name": "Terraced Slope",
    "confidence": 1,
    "category": "Gardens",
    "broader": [
      104,
      105,
      160,
      168
    ],
    "narrower": [
      172,
      245,
      247
    ]
  },
  {
    "id": 170,
    "name": "Fruit Trees",
    "confidence": 1,
    "category": "Gardens",
    "broader": [
      52,
      67,
      111
    ],
    "narrower": [
      171,
      172,
      174,
      177,
      178,
      243,
      245
    ]
  },
  {
    "id": 171,
    "name": "Tree Places",
    "confidence": 2,
    "category": "Gardens",
    "broader": [
      25,
      60,
      71,
      104,
      105,
      121,
      170
    ],
    "narrower": [
      120,
      172,
      174,
      176
    ]
  },
  {
    "id": 172,
    "name": "Garden Growing Wild",
    "confidence": 2,
    "category": "Gardens",
    "broader": [
      74,
      105,
      107,
      112,
      169,
      170,
      171
    ],
    "narrower": [
      163,
      174,
      176,
      241,
      243
    ]
  },
  {
    "id": 173,
    "name": "Garden Wall",
    "confidence": 1,
    "category": "Gardens",
    "broader": [
      57,
      59,
      60,
      66,
      69,
      74,
      111,
      112,
      113,
      116,
      140,
      145,
      164
    ],
    "narrower": [
      71,
      175,
      176,
      245,
      249
    ]
  },
  {
    "id": 174,
    "name": "Trellised Walk",
    "confidence": 2,
    "category": "Gardens",
    "broader": [
      55,
      72,
      106,
      112,
      113,
      120,
      125,
      162,
      163,
      164,
      170,
      171,
      172,
      175
    ],
    "narrower": [
      106,
      114,
      134,
      140,
      193,
      226,
      241,
      244,
      246
    ]
  },
  {
    "id": 175,
    "name": "Greenhouse",
    "confidence": 0,
    "category": "Gardens",
    "broader": [
      37,
      41,
      67,
      173
    ],
    "narrower": [
      174,
      226,
      238,
      246,
      247
    ]
  },
  {
    "id": 176,
    "name": "Garden Seat",
    "confidence": 0,
    "category": "Gardens",
    "broader": [
      25,
      115,
      151,
      161,
      171,
      172,
      173
    ],
    "narrower": [
      180,
      241
    ]
  },
  {
    "id": 177,
    "name": "Vegetable Garden",
    "confidence": 1,
    "category": "Gardens",
    "broader": [
      40,
      48,
      67,
      68,
      170
    ],
    "narrower": [
      178,
      238,
      241
    ]
  },
  {
    "id": 178,
    "name": "Compost",
    "confidence": 1,
    "category": "Gardens",
    "broader": [
      37,
      69,
      74,
      145,
      170,
      177,
      182
    ],
    "narrower": [
      144
    ]
  },
  {
    "id": 179,
    "name": "Alcoves",
    "confidence": 2,
    "category": "Alcoves",
    "broader": [
      65,
      129,
      133,
      139,
      140,
      142,
      146,
      150,
      151,
      181,
      187,
      194,
      229
    ],
    "narrower": [
      183,
      252
    ]
  },
  {
    "id": 180,
    "name": "Window Place",
    "confidence": 2,
    "category": "Alcoves",
    "broader": [
      79,
      102,
      130,
      133,
      134,
      135,
      143,
      150,
      151,
      159,
      160,
      164,
      165,
      176,
      182,
      186,
      198
    ],
    "narrower": [
      190,
      191,
      193,
      201,
      202,
      221,
      222,
      226,
      231,
      236,
      244,
      249
    ]
  },
  {
    "id": 181,
    "name": "The Fire",
    "confidence": 1,
    "category": "Alcoves",
    "broader": [
      129,
      130,
      143,
      150,
      186
    ],
    "narrower": [
      179,
      202,
      221,
      222,
      223,
      231
    ]
  },
  {
    "id": 182,
    "name": "Eating Atmosphere",
    "confidence": 0,
    "category": "Alcoves",
    "broader": [
      139,
      140,
      147,
      148
    ],
    "narrower": [
      178,
      180,
      185,
      252
    ]
  },
  {
    "id": 183,
    "name": "Workspace Enclosure",
    "confidence": 2,
    "category": "Alcoves",
    "broader": [
      79,
      129,
      142,
      146,
      149,
      150,
      152,
      157,
      158,
      179,
      194
    ],
    "narrower": [
      198,
      200,
      201,
      202,
      250,
      251,
      252
    ]
  },
  {
    "id": 184,
    "name": "Cooking Layout",
    "confidence": 1,
    "category": "Alcoves",
    "broader": [
      139,
      140
    ],
    "narrower": [
      185,
      191,
      192,
      193,
      197,
      199,
      200,
      201,
      252
    ]
  },
  {
    "id": 185,
    "name": "Sitting Circle",
    "confidence": 1,
    "category": "Alcoves",
    "broader": [
      127,
      142,
      143,
      155,
      182,
      184
    ],
    "narrower": [
      197,
      199,
      200,
      251,
      252
    ]
  },
  {
    "id": 186,
    "name": "Communal Sleeping",
    "confidence": 0,
    "category": "Alcoves",
    "broader": [
      92,
      136,
      137,
      138,
      143,
      144,
      187,
      188
    ],
    "narrower": [
      129,
      142,
      180,
      181,
      188,
      191,
      193,
      251,
      252
    ]
  },
  {
    "id": 187,
    "name": "Marriage Bed",
    "confidence": 0,
    "category": "Alcoves",
    "broader": [
      27,
      136
    ],
    "narrower": [
      143,
      179,
      186,
      188,
      189
    ]
  },
  {
    "id": 188,
    "name": "Bed Alcove",
    "confidence": 2,
    "category": "Alcoves",
    "broader": [
      79,
      141,
      142,
      143,
      144,
      155,
      186,
      187
    ],
    "narrower": [
      186,
      189,
      190,
      249
    ]
  },
  {
    "id": 189,
    "name": "Dressing Rooms",
    "confidence": 1,
    "category": "Alcoves",
    "broader": [
      79,
      142,
      144,
      187,
      188
    ],
    "narrower": [
      190,
      191,
      193,
      197,
      198,
      200,
      221
    ]
  },
  {
    "id": 190,
    "name": "Ceiling Height Variety",
    "confidence": 0,
    "category": "Room Shapes",
    "broader": [
      102,
      117,
      120,
      180,
      188,
      189
    ],
    "narrower": [
      191,
      192,
      204,
      210,
      213
    ]
  },
  {
    "id": 191,
    "name": "The Shape of Indoor Space",
    "confidence": 0,
    "category": "Room Shapes",
    "broader": [
      88,
      90,
      130,
      134,
      142,
      143,
      144,
      150,
      151,
      155,
      156,
      158,
      164,
      168,
      180,
      184,
      186,
      189,
      190
    ],
    "narrower": [
      145,
      192,
      205,
      213,
      219
    ]
  },
  {
    "id": 192,
    "name": "Windows Overlooking Life",
    "confidence": 0,
    "category": "Room Shapes",
    "broader": [
      158,
      159,
      160,
      184,
      190,
      191,
      200
    ],
    "narrower": [
      106,
      193,
      197,
      198,
      205,
      210,
      212,
      218,
      219,
      221,
      222,
      236
    ]
  },
  {
    "id": 193,
    "name": "Half-Open Wall",
    "confidence": 0,
    "category": "Room Shapes",
    "broader": [
      120,
      168,
      174,
      180,
      184,
      186,
      189,
      192
    ],
    "narrower": [
      194
    ]
  },
  {
    "id": 194,
    "name": "Interior Windows",
    "confidence": 0,
    "category": "Room Shapes",
    "broader": [
      101,
      102,
      130,
      131,
      132,
      133,
      135,
      142,
      193
    ],
    "narrower": [
      179,
      183,
      212,
      226,
      227,
      237,
      239,
      249
    ]
  },
  {
    "id": 195,
    "name": "Staircase Volume",
    "confidence": 1,
    "category": "Room Shapes",
    "broader": [
      134
    ],
    "narrower": [
      228,
      237,
      239
    ]
  },
  {
    "id": 196,
    "name": "Corner Doors",
    "confidence": 1,
    "category": "Room Shapes",
    "broader": [
      131,
      132,
      135,
      142
    ],
    "narrower": [
      125,
      198,
      203,
      212,
      221,
      224,
      228,
      237,
      249
    ]
  },
  {
    "id": 197,
    "name": "Thick Walls",
    "confidence": 0,
    "category": "Walls",
    "broader": [
      88,
      90,
      133,
      184,
      185,
      189,
      192,
      199,
      203,
      224
    ],
    "narrower": [
      200,
      201,
      203,
      204
    ]
  },
  {
    "id": 198,
    "name": "Closets Between Rooms",
    "confidence": 0,
    "category": "Walls",
    "broader": [
      69,
      133,
      144,
      183,
      189,
      192,
      196,
      229
    ],
    "narrower": [
      180,
      199,
      200,
      201,
      202,
      203,
      204,
      212
    ]
  },
  {
    "id": 199,
    "name": "Sunny Counter",
    "confidence": 1,
    "category": "Walls",
    "broader": [
      128,
      129,
      139,
      140,
      184,
      185,
      198
    ],
    "narrower": [
      197,
      201
    ]
  },
  {
    "id": 200,
    "name": "Open Shelves",
    "confidence": 1,
    "category": "Walls",
    "broader": [
      88,
      90,
      139,
      140,
      183,
      184,
      185,
      189,
      197,
      198
    ],
    "narrower": [
      192,
      250
    ]
  },
  {
    "id": 201,
    "name": "Waist-High Shelf",
    "confidence": 0,
    "category": "Walls",
    "broader": [
      116,
      131,
      140,
      180,
      183,
      184,
      197,
      198,
      199,
      202,
      203,
      204,
      223
    ],
    "narrower": [
      212,
      213,
      233
    ]
  },
  {
    "id": 202,
    "name": "Built-In Seats",
    "confidence": 0,
    "category": "Walls",
    "broader": [
      131,
      180,
      181,
      183,
      198,
      231
    ],
    "narrower": [
      201,
      251
    ]
  },
  {
    "id": 203,
    "name": "Child Caves",
    "confidence": 0,
    "category": "Walls",
    "broader": [
      73,
      74,
      86,
      137,
      144,
      196,
      197,
      198,
      229
    ],
    "narrower": [
      197,
      201
    ]
  },
  {
    "id": 204,
    "name": "Secret Place",
    "confidence": 0,
    "category": "Walls",
    "broader": [
      190,
      197,
      198
    ],
    "narrower": [
      201,
      224
    ]
  },
  {
    "id": 205,
    "name": "Structure Follows Social Spaces",
    "confidence": 0,
    "category": "Philosophy of Structure",
    "broader": [
      96,
      97,
      98,
      100,
      114,
      117,
      120,
      155,
      156,
      164,
      191,
      192,
      208
    ],
    "narrower": [
      206,
      207,
      208,
      212
    ]
  },
  {
    "id": 206,
    "name": "Efficient Structure",
    "confidence": 1,
    "category": "Philosophy of Structure",
    "broader": [
      205,
      208
    ],
    "narrower": [
      207,
      208,
      210,
      213,
      215,
      218,
      225,
      227,
      228,
      229
    ]
  },
  {
    "id": 207,
    "name": "Good Materials",
    "confidence": 2,
    "category": "Philosophy of Structure",
    "broader": [
      205,
      206
    ],
    "narrower": [
      208,
      209,
      210,
      212,
      213,
      216,
      217,
      218,
      219,
      220,
      225,
      227,
      228,
      248,
      250
    ]
  },
  {
    "id": 208,
    "name": "Gradual Stiffening",
    "confidence": 2,
    "category": "Philosophy of Structure",
    "broader": [
      205,
      206,
      207
    ],
    "narrower": [
      205,
      206,
      212,
      225,
      234,
      235
    ]
  },
  {
    "id": 209,
    "name": "Roof Layout",
    "confidence": 1,
    "category": "Structural Layout",
    "broader": [
      116,
      117,
      118,
      207
    ],
    "narrower": [
      210,
      212
    ]
  },
  {
    "id": 210,
    "name": "Floor and Ceiling Layout",
    "confidence": 0,
    "category": "Structural Layout",
    "broader": [
      190,
      192,
      206,
      207,
      209
    ],
    "narrower": [
      212,
      217
    ]
  },
  {
    "id": 211,
    "name": "Thickening the Outer Walls",
    "confidence": 0,
    "category": "Walls",
    "broader": [],
    "narrower": []
  },
  {
    "id": 212,
    "name": "Columns at the Corners",
    "confidence": 0,
    "category": "Structural Layout",
    "broader": [
      47,
      192,
      194,
      196,
      198,
      201,
      205,
      207,
      208,
      209,
      210
    ],
    "narrower": [
      213,
      214,
      215,
      219,
      226
    ]
  },
  {
    "id": 213,
    "name": "Final Column Distribution",
    "confidence": 0,
    "category": "Structural Layout",
    "broader": [
      97,
      190,
      191,
      201,
      206,
      207,
      212
    ],
    "narrower": [
      214,
      216,
      217,
      218,
      226
    ]
  },
  {
    "id": 214,
    "name": "Root Foundations",
    "confidence": 0,
    "category": "Structural Frame",
    "broader": [
      104,
      168,
      212,
      213,
      217
    ],
    "narrower": [
      215,
      216
    ]
  },
  {
    "id": 215,
    "name": "Ground Floor Slab",
    "confidence": 0,
    "category": "Structural Frame",
    "broader": [
      168,
      206,
      212,
      214
    ],
    "narrower": [
      216,
      233
    ]
  },
  {
    "id": 216,
    "name": "Box Columns",
    "confidence": 2,
    "category": "Structural Frame",
    "broader": [
      207,
      213,
      214,
      215,
      227
    ],
    "narrower": [
      168,
      217,
      218,
      219,
      221,
      227,
      248
    ]
  },
  {
    "id": 217,
    "name": "Perimeter Beams",
    "confidence": 1,
    "category": "Structural Frame",
    "broader": [
      207,
      210,
      213,
      216,
      219
    ],
    "narrower": [
      214,
      219,
      221,
      226,
      227
    ]
  },
  {
    "id": 218,
    "name": "Wall Membranes",
    "confidence": 1,
    "category": "Structural Frame",
    "broader": [
      192,
      206,
      207,
      213,
      216,
      236,
      238
    ],
    "narrower": [
      219,
      227,
      230,
      234,
      235
    ]
  },
  {
    "id": 219,
    "name": "Floor-Ceiling Vaults",
    "confidence": 0,
    "category": "Structural Frame",
    "broader": [
      191,
      192,
      207,
      212,
      216,
      217,
      218,
      229,
      230,
      236
    ],
    "narrower": [
      217,
      220,
      229,
      230,
      233,
      235
    ]
  },
  {
    "id": 220,
    "name": "Roof Vaults",
    "confidence": 0,
    "category": "Structural Frame",
    "broader": [
      117,
      118,
      207,
      219
    ],
    "narrower": [
      231,
      232,
      233,
      234,
      235
    ]
  },
  {
    "id": 221,
    "name": "Natural Doors and Windows",
    "confidence": 0,
    "category": "Openings",
    "broader": [
      134,
      135,
      160,
      164,
      180,
      181,
      189,
      192,
      196,
      216,
      217,
      225
    ],
    "narrower": [
      222,
      224,
      225,
      236,
      238,
      239
    ]
  },
  {
    "id": 222,
    "name": "Low Sill",
    "confidence": 0,
    "category": "Openings",
    "broader": [
      133,
      134,
      180,
      181,
      192,
      221
    ],
    "narrower": [
      223,
      239
    ]
  },
  {
    "id": 223,
    "name": "Deep Reveals",
    "confidence": 0,
    "category": "Openings",
    "broader": [
      1,
      2,
      159,
      160,
      181,
      222,
      225
    ],
    "narrower": [
      201,
      225,
      236,
      238,
      245
    ]
  },
  {
    "id": 224,
    "name": "Low Doorway",
    "confidence": 0,
    "category": "Openings",
    "broader": [
      102,
      110,
      120,
      131,
      196,
      204,
      221
    ],
    "narrower": [
      197,
      225,
      237,
      238,
      240,
      246
    ]
  },
  {
    "id": 225,
    "name": "Frames As Thickened Edges",
    "confidence": 0,
    "category": "Openings",
    "broader": [
      206,
      207,
      208,
      221,
      223,
      224
    ],
    "narrower": [
      221,
      223,
      227,
      237,
      239,
      249
    ]
  },
  {
    "id": 226,
    "name": "Column Place",
    "confidence": 1,
    "category": "Structural Subsidiaries",
    "broader": [
      69,
      119,
      120,
      163,
      164,
      166,
      167,
      168,
      174,
      175,
      180,
      194,
      212,
      213,
      217,
      228
    ],
    "narrower": [
      227,
      249
    ]
  },
  {
    "id": 227,
    "name": "Column Connections",
    "confidence": 2,
    "category": "Structural Subsidiaries",
    "broader": [
      119,
      120,
      166,
      167,
      194,
      206,
      207,
      216,
      217,
      218,
      225,
      226
    ],
    "narrower": [
      216,
      243,
      245,
      249,
      251
    ]
  },
  {
    "id": 228,
    "name": "Stair Vault",
    "confidence": 1,
    "category": "Structural Subsidiaries",
    "broader": [
      133,
      195,
      196,
      206,
      207
    ],
    "narrower": [
      226,
      249
    ]
  },
  {
    "id": 229,
    "name": "Duct Space",
    "confidence": 0,
    "category": "Structural Subsidiaries",
    "broader": [
      206,
      219
    ],
    "narrower": [
      179,
      198,
      203,
      219,
      230
    ]
  },
  {
    "id": 230,
    "name": "Radiant Heat",
    "confidence": 1,
    "category": "Structural Subsidiaries",
    "broader": [
      218,
      219,
      229
    ],
    "narrower": [
      219,
      252
    ]
  },
  {
    "id": 231,
    "name": "Dormer Windows",
    "confidence": 1,
    "category": "Structural Subsidiaries",
    "broader": [
      117,
      118,
      180,
      181,
      220
    ],
    "narrower": [
      202
    ]
  },
  {
    "id": 232,
    "name": "Roof Caps",
    "confidence": 0,
    "category": "Structural Subsidiaries",
    "broader": [
      118,
      220
    ],
    "narrower": [
      236,
      239,
      249
    ]
  },
  {
    "id": 233,
    "name": "Floor Surface",
    "confidence": 2,
    "category": "Surfaces",
    "broader": [
      127,
      201,
      215,
      219,
      220
    ],
    "narrower": [
      248,
      250
    ]
  },
  {
    "id": 234,
    "name": "Lapped Outside Walls",
    "confidence": 0,
    "category": "Surfaces",
    "broader": [
      208,
      218,
      220
    ],
    "narrower": [
      248,
      249,
      250
    ]
  },
  {
    "id": 235,
    "name": "Soft Inside Walls",
    "confidence": 1,
    "category": "Surfaces",
    "broader": [
      208,
      218,
      219,
      220
    ],
    "narrower": [
      249,
      250
    ]
  },
  {
    "id": 236,
    "name": "Windows Which Open Wide",
    "confidence": 0,
    "category": "Surfaces",
    "broader": [
      129,
      165,
      180,
      192,
      221,
      223,
      232
    ],
    "narrower": [
      218,
      219,
      239,
      240
    ]
  },
  {
    "id": 237,
    "name": "Solid Doors With Glass",
    "confidence": 0,
    "category": "Surfaces",
    "broader": [
      102,
      131,
      133,
      135,
      194,
      195,
      196,
      224,
      225
    ],
    "narrower": [
      239
    ]
  },
  {
    "id": 238,
    "name": "Filtered Light",
    "confidence": 1,
    "category": "Surfaces",
    "broader": [
      145,
      160,
      162,
      165,
      175,
      177,
      221,
      223,
      224,
      245
    ],
    "narrower": [
      218,
      244,
      246
    ]
  },
  {
    "id": 239,
    "name": "Small Panes",
    "confidence": 2,
    "category": "Surfaces",
    "broader": [
      194,
      195,
      221,
      222,
      225,
      232,
      236,
      237
    ],
    "narrower": [
      244,
      246,
      250
    ]
  },
  {
    "id": 240,
    "name": "Half-Inch Trim",
    "confidence": 0,
    "category": "Surfaces",
    "broader": [
      224,
      236,
      250,
      251
    ],
    "narrower": []
  },
  {
    "id": 241,
    "name": "Seat Spots",
    "confidence": 2,
    "category": "Outdoor Details",
    "broader": [
      70,
      71,
      73,
      121,
      124,
      125,
      126,
      140,
      143,
      160,
      161,
      162,
      163,
      168,
      172,
      174,
      176,
      177,
      243
    ],
    "narrower": [
      242
    ]
  },
  {
    "id": 242,
    "name": "Front Door Bench",
    "confidence": 1,
    "category": "Outdoor Details",
    "broader": [
      119,
      123,
      130,
      131,
      155,
      156,
      161,
      168,
      241
    ],
    "narrower": [
      125,
      243
    ]
  },
  {
    "id": 243,
    "name": "Sitting Wall",
    "confidence": 1,
    "category": "Outdoor Details",
    "broader": [
      51,
      56,
      72,
      73,
      74,
      89,
      100,
      106,
      114,
      121,
      124,
      125,
      140,
      163,
      164,
      165,
      166,
      168,
      170,
      172,
      227,
      242
    ],
    "narrower": [
      110,
      241,
      245,
      248,
      249
    ]
  },
  {
    "id": 244,
    "name": "Canvas Roofs",
    "confidence": 1,
    "category": "Outdoor Details",
    "broader": [
      33,
      47,
      55,
      59,
      64,
      70,
      89,
      94,
      98,
      103,
      118,
      119,
      140,
      162,
      163,
      164,
      166,
      174,
      180,
      238,
      239,
      251
    ],
    "narrower": [
      245
    ]
  },
  {
    "id": 245,
    "name": "Raised Flowers",
    "confidence": 1,
    "category": "Outdoor Details",
    "broader": [
      52,
      114,
      120,
      121,
      125,
      160,
      169,
      170,
      173,
      223,
      227,
      243,
      244
    ],
    "narrower": [
      238,
      249,
      250
    ]
  },
  {
    "id": 246,
    "name": "Climbing Plants",
    "confidence": 0,
    "category": "Outdoor Details",
    "broader": [
      165,
      174,
      175,
      224,
      238,
      239
    ],
    "narrower": []
  },
  {
    "id": 247,
    "name": "Paving With Cracks Between the Stones",
    "confidence": 0,
    "category": "Outdoor Details",
    "broader": [
      51,
      52,
      121,
      140,
      163,
      168,
      169,
      175
    ],
    "narrower": [
      248
    ]
  },
  {
    "id": 248,
    "name": "Soft Tile and Brick",
    "confidence": 0,
    "category": "Outdoor Details",
    "broader": [
      126,
      168,
      207,
      216,
      233,
      234,
      243,
      247,
      251
    ],
    "narrower": [
      168
    ]
  },
  {
    "id": 249,
    "name": "Ornament",
    "confidence": 2,
    "category": "Ornamentation",
    "broader": [
      110,
      160,
      168,
      173,
      180,
      188,
      194,
      196,
      225,
      226,
      227,
      228,
      232,
      234,
      235,
      243,
      245,
      251
    ],
    "narrower": []
  },
  {
    "id": 250,
    "name": "Warm Colors",
    "confidence": 2,
    "category": "Ornamentation",
    "broader": [
      183,
      200,
      207,
      233,
      234,
      235,
      239,
      245,
      253
    ],
    "narrower": [
      240,
      252,
      253
    ]
  },
  {
    "id": 251,
    "name": "Different Chairs",
    "confidence": 0,
    "category": "Ornamentation",
    "broader": [
      89,
      142,
      183,
      185,
      186,
      202,
      227
    ],
    "narrower": [
      240,
      244,
      248,
      249,
      252
    ]
  },
  {
    "id": 252,
    "name": "Pools of Light",
    "confidence": 2,
    "category": "Ornamentation",
    "broader": [
      129,
      130,
      146,
      179,
      182,
      183,
      184,
      185,
      186,
      230,
      250,
      251
    ],
    "narrower": []
  },
  {
    "id": 253,
    "name": "Things From Your Life",
    "confidence": 0,
    "category": "Ornamentation",
    "broader": [
      142,
      250
    ],
    "narrower": [
      250
    ]
  }
] satisfies readonly PatternData[] as unknown as readonly Pattern[]
