// GENERATED by scripts/convert.ts — do not edit by hand.
// Source: data-notes/patterns-extracted.json (see data-notes/LICENSE-data
// for provenance). Prose gists come from data-notes/gists.json.
// Regenerate with: npm run data:convert

import type { Pattern, PatternData } from './schema'

export const patterns = [
  {
    "id": 1,
    "name": "Independent Regions",
    "confidence": 2,
    "category": "Network of Lattices",
    "broader": [],
    "narrower": [
      2,
      4
    ]
  },
  {
    "id": 2,
    "name": "The Distribution of Towns",
    "confidence": 0,
    "category": "Regional Policies",
    "broader": [
      1
    ],
    "narrower": [
      3,
      4,
      6,
      7
    ]
  },
  {
    "id": 3,
    "name": "City Country Fingers",
    "confidence": 2,
    "category": "Regional Policies",
    "broader": [
      2
    ],
    "narrower": [
      4,
      5,
      7,
      8,
      10,
      11,
      16,
      17,
      21
    ]
  },
  {
    "id": 4,
    "name": "Agricultural Valleys",
    "confidence": 1,
    "category": "Regional Policies",
    "broader": [
      1,
      2,
      3
    ],
    "narrower": [
      7
    ]
  },
  {
    "id": 5,
    "name": "Lace of Country Streets",
    "confidence": 0,
    "category": "Regional Policies",
    "broader": [
      3
    ],
    "narrower": [
      7,
      14,
      21,
      37
    ]
  },
  {
    "id": 6,
    "name": "Country Towns",
    "confidence": 1,
    "category": "Regional Policies",
    "broader": [
      2
    ],
    "narrower": [
      7,
      12,
      26
    ]
  },
  {
    "id": 7,
    "name": "The Countryside",
    "confidence": 1,
    "category": "Regional Policies",
    "broader": [
      2,
      3,
      4,
      5,
      6,
      13,
      25,
      114
    ],
    "narrower": [
      37,
      51
    ]
  },
  {
    "id": 8,
    "name": "Mosaic of Subcultures",
    "confidence": 2,
    "category": "City Policies",
    "broader": [
      3
    ],
    "narrower": [
      9,
      10,
      11,
      12,
      13,
      14,
      19,
      29,
      31,
      37
    ]
  },
  {
    "id": 9,
    "name": "Scattered Work",
    "confidence": 2,
    "category": "City Policies",
    "broader": [
      8,
      27,
      34
    ],
    "narrower": [
      13,
      15,
      19,
      41,
      42,
      59,
      80,
      157
    ]
  },
  {
    "id": 10,
    "name": "Magic of the City",
    "confidence": 0,
    "category": "City Policies",
    "broader": [
      3,
      8,
      19
    ],
    "narrower": [
      11,
      16,
      21,
      28,
      31,
      32,
      33,
      58,
      63,
      91
    ]
  },
  {
    "id": 11,
    "name": "Local Transport Areas",
    "confidence": 2,
    "category": "City Policies",
    "broader": [
      3,
      8,
      10
    ],
    "narrower": [
      16,
      17,
      19,
      20,
      22,
      23,
      34,
      49,
      51,
      52,
      56,
      97
    ]
  },
  {
    "id": 12,
    "name": "Community of 7000",
    "confidence": 1,
    "category": "Communities",
    "broader": [
      6,
      8
    ],
    "narrower": [
      13,
      14,
      15,
      22,
      26,
      27,
      28,
      29,
      30,
      31,
      33,
      44,
      62,
      65
    ]
  },
  {
    "id": 13,
    "name": "Subculture Boundary",
    "confidence": 1,
    "category": "Communities",
    "broader": [
      8,
      9,
      12,
      14
    ],
    "narrower": [
      7,
      15,
      17,
      19,
      23,
      24,
      25,
      28,
      29,
      30,
      41,
      42,
      48,
      60,
      64,
      71,
      84,
      97
    ]
  },
  {
    "id": 14,
    "name": "Identifiable Neighborhood",
    "confidence": 2,
    "category": "Communities",
    "broader": [
      5,
      8,
      12
    ],
    "narrower": [
      13,
      15,
      22,
      26,
      27,
      30,
      35,
      36,
      37,
      40,
      41,
      48,
      49,
      53,
      60,
      61,
      65,
      70,
      88,
      89
    ]
  },
  {
    "id": 15,
    "name": "Neighborhood Boundary",
    "confidence": 1,
    "category": "Communities",
    "broader": [
      9,
      12,
      13,
      14
    ],
    "narrower": [
      23,
      30,
      32,
      41,
      48,
      53,
      59,
      60,
      64,
      69,
      70,
      72,
      73,
      90,
      97,
      103
    ]
  },
  {
    "id": 16,
    "name": "Web of Public Transport",
    "confidence": 1,
    "category": "Community Networking",
    "broader": [
      3,
      10,
      11
    ],
    "narrower": [
      17,
      20,
      34
    ]
  },
  {
    "id": 17,
    "name": "Ring Roads",
    "confidence": 0,
    "category": "Community Networking",
    "broader": [
      3,
      11,
      13,
      16,
      34
    ],
    "narrower": [
      23,
      25,
      42,
      97
    ]
  },
  {
    "id": 18,
    "name": "Network of Learning",
    "confidence": 1,
    "category": "Community Networking",
    "broader": [
      40
    ],
    "narrower": [
      43,
      57,
      83,
      84,
      85,
      86,
      157
    ]
  },
  {
    "id": 19,
    "name": "Web of Shopping",
    "confidence": 1,
    "category": "Community Networking",
    "broader": [
      8,
      9,
      11,
      13
    ],
    "narrower": [
      10,
      31,
      32,
      46,
      89
    ]
  },
  {
    "id": 20,
    "name": "Mini-Buses",
    "confidence": 1,
    "category": "Community Networking",
    "broader": [
      11,
      16
    ],
    "narrower": [
      23,
      34,
      92
    ]
  },
  {
    "id": 21,
    "name": "Four-Story Limit",
    "confidence": 2,
    "category": "Community Policies",
    "broader": [
      3,
      5,
      10
    ],
    "narrower": [
      28,
      29,
      39,
      62,
      82,
      95,
      96
    ]
  },
  {
    "id": 22,
    "name": "Nine Per Cent Parking",
    "confidence": 2,
    "category": "Community Policies",
    "broader": [
      11,
      12,
      14
    ],
    "narrower": [
      97,
      103
    ]
  },
  {
    "id": 23,
    "name": "Parallel Roads",
    "confidence": 0,
    "category": "Community Policies",
    "broader": [
      11,
      13,
      15,
      17,
      20,
      25,
      32,
      38
    ],
    "narrower": [
      49,
      50,
      51,
      52,
      54,
      55,
      57
    ]
  },
  {
    "id": 24,
    "name": "Sacred Sites",
    "confidence": 1,
    "category": "Community Policies",
    "broader": [
      13,
      28,
      59,
      134,
      171,
      176
    ],
    "narrower": [
      25,
      64,
      66
    ]
  },
  {
    "id": 25,
    "name": "Access to Water",
    "confidence": 1,
    "category": "Community Policies",
    "broader": [
      13,
      17,
      24
    ],
    "narrower": [
      7,
      23,
      31,
      64,
      71,
      103
    ]
  },
  {
    "id": 26,
    "name": "Life Cycle",
    "confidence": 1,
    "category": "Community Policies",
    "broader": [
      6,
      12,
      14
    ],
    "narrower": [
      27,
      35,
      40,
      41,
      44,
      47,
      57,
      65,
      66,
      70,
      75,
      79,
      83,
      84,
      85,
      86,
      153,
      154,
      155,
      156,
      187
    ]
  },
  {
    "id": 27,
    "name": "Men and Women",
    "confidence": 0,
    "category": "Community Policies",
    "broader": [
      12,
      14,
      26
    ],
    "narrower": [
      9,
      141,
      157
    ]
  },
  {
    "id": 28,
    "name": "Eccentric Nucleus",
    "confidence": 1,
    "category": "Local Centers",
    "broader": [
      10,
      12,
      13,
      21
    ],
    "narrower": [
      24,
      29,
      30,
      31,
      32,
      59,
      71
    ]
  },
  {
    "id": 29,
    "name": "Density Rings",
    "confidence": 1,
    "category": "Local Centers",
    "broader": [
      8,
      12,
      13,
      21,
      28
    ],
    "narrower": [
      30,
      31,
      36,
      37,
      38,
      39,
      61,
      123
    ]
  },
  {
    "id": 30,
    "name": "Activity Nodes",
    "confidence": 2,
    "category": "Local Centers",
    "broader": [
      12,
      13,
      14,
      15,
      28,
      29,
      34,
      100
    ],
    "narrower": [
      31,
      33,
      36,
      41,
      43,
      44,
      47,
      52,
      61,
      65,
      84,
      85,
      87,
      88,
      90,
      91,
      93,
      120
    ]
  },
  {
    "id": 31,
    "name": "Promenade",
    "confidence": 2,
    "category": "Local Centers",
    "broader": [
      8,
      10,
      12,
      19,
      25,
      28,
      29,
      30,
      43,
      64
    ],
    "narrower": [
      32,
      33,
      52,
      57,
      58,
      61,
      63,
      90,
      91,
      100,
      121,
      123,
      124
    ]
  },
  {
    "id": 32,
    "name": "Shopping Street",
    "confidence": 1,
    "category": "Local Centers",
    "broader": [
      10,
      15,
      19,
      28,
      31
    ],
    "narrower": [
      23,
      46,
      48,
      52,
      54,
      87,
      97,
      100,
      103,
      121,
      244
    ]
  },
  {
    "id": 33,
    "name": "Night Life",
    "confidence": 1,
    "category": "Local Centers",
    "broader": [
      10,
      12,
      30,
      31
    ],
    "narrower": [
      44,
      58,
      63,
      88,
      90,
      91
    ]
  },
  {
    "id": 34,
    "name": "Interchange",
    "confidence": 0,
    "category": "Local Centers",
    "broader": [
      11,
      16,
      20
    ],
    "narrower": [
      9,
      17,
      30,
      39,
      40,
      41,
      92,
      94,
      119,
      150
    ]
  },
  {
    "id": 35,
    "name": "Household Mix",
    "confidence": 1,
    "category": "Housing Clusters",
    "broader": [
      14,
      26,
      41
    ],
    "narrower": [
      37,
      40,
      68,
      75,
      76,
      77,
      78
    ]
  },
  {
    "id": 36,
    "name": "Degrees of Publicness",
    "confidence": 2,
    "category": "Housing Clusters",
    "broader": [
      14,
      29,
      30
    ],
    "narrower": [
      37,
      38,
      39,
      51,
      55,
      100,
      120,
      121,
      123
    ]
  },
  {
    "id": 37,
    "name": "House Cluster",
    "confidence": 2,
    "category": "Housing Clusters",
    "broader": [
      5,
      7,
      8,
      14,
      29,
      35,
      36,
      47,
      68
    ],
    "narrower": [
      38,
      39,
      48,
      49,
      53,
      67,
      71,
      75,
      76,
      77,
      78,
      79,
      98,
      103,
      111,
      157,
      175,
      178
    ]
  },
  {
    "id": 38,
    "name": "Row Houses",
    "confidence": 1,
    "category": "Housing Clusters",
    "broader": [
      29,
      36,
      37,
      47,
      48
    ],
    "narrower": [
      23,
      52,
      67,
      75,
      76,
      77,
      78,
      79,
      95,
      100,
      103,
      109,
      111
    ]
  },
  {
    "id": 39,
    "name": "Housing Hill",
    "confidence": 0,
    "category": "Housing Clusters",
    "broader": [
      21,
      29,
      34,
      36,
      37,
      97
    ],
    "narrower": [
      67,
      68,
      75,
      79,
      100,
      118,
      158,
      177
    ]
  },
  {
    "id": 40,
    "name": "Old People Everywhere",
    "confidence": 2,
    "category": "Housing Clusters",
    "broader": [
      14,
      26,
      34,
      35,
      57
    ],
    "narrower": [
      18,
      75,
      86,
      155,
      156,
      177
    ]
  },
  {
    "id": 41,
    "name": "Work Community",
    "confidence": 2,
    "category": "Work Communities",
    "broader": [
      9,
      13,
      14,
      15,
      26,
      30,
      34,
      57
    ],
    "narrower": [
      35,
      42,
      48,
      49,
      53,
      59,
      60,
      61,
      67,
      71,
      72,
      80,
      81,
      82,
      88,
      91,
      93,
      103,
      111,
      115,
      147,
      175
    ]
  },
  {
    "id": 42,
    "name": "Industrial Ribbon",
    "confidence": 1,
    "category": "Work Communities",
    "broader": [
      9,
      13,
      17,
      41
    ],
    "narrower": [
      80,
      106,
      122
    ]
  },
  {
    "id": 43,
    "name": "University as a Marketplace",
    "confidence": 0,
    "category": "Work Communities",
    "broader": [
      18,
      30,
      57
    ],
    "narrower": [
      31,
      45,
      48,
      59,
      81,
      83,
      95,
      100,
      151,
      165
    ]
  },
  {
    "id": 44,
    "name": "Local Town Hall",
    "confidence": 1,
    "category": "Work Communities",
    "broader": [
      12,
      26,
      30,
      33
    ],
    "narrower": [
      45,
      61,
      81,
      123,
      151,
      165
    ]
  },
  {
    "id": 45,
    "name": "Necklace of Community Projects",
    "confidence": 0,
    "category": "Work Communities",
    "broader": [
      43,
      44,
      47,
      81
    ],
    "narrower": [
      69,
      87,
      122,
      153,
      160,
      165
    ]
  },
  {
    "id": 46,
    "name": "Market of Many Shops",
    "confidence": 2,
    "category": "Work Communities",
    "broader": [
      19,
      32
    ],
    "narrower": [
      87,
      89,
      100,
      101,
      165,
      212,
      244
    ]
  },
  {
    "id": 47,
    "name": "Health Center",
    "confidence": 1,
    "category": "Work Communities",
    "broader": [
      26,
      30
    ],
    "narrower": [
      37,
      38,
      45,
      71,
      72,
      79,
      81,
      150,
      165
    ]
  },
  {
    "id": 48,
    "name": "Housing In Between",
    "confidence": 2,
    "category": "Work Communities",
    "broader": [
      13,
      14,
      15,
      32,
      37,
      41,
      43,
      97
    ],
    "narrower": [
      38,
      75,
      79
    ]
  },
  {
    "id": 49,
    "name": "Looped Local Roads",
    "confidence": 2,
    "category": "Local Networking",
    "broader": [
      11,
      14,
      23,
      37,
      41,
      114
    ],
    "narrower": [
      50,
      51,
      52,
      56,
      57,
      103,
      113
    ]
  },
  {
    "id": 50,
    "name": "T Junctions",
    "confidence": 1,
    "category": "Local Networking",
    "broader": [
      23,
      49
    ],
    "narrower": [
      51,
      54
    ]
  },
  {
    "id": 51,
    "name": "Green Streets",
    "confidence": 2,
    "category": "Local Networking",
    "broader": [
      7,
      11,
      23,
      36,
      49,
      50,
      68,
      114
    ],
    "narrower": [
      52,
      57,
      67,
      74,
      103,
      140,
      164,
      170,
      243,
      245,
      247
    ]
  },
  {
    "id": 52,
    "name": "Network of Paths and Cars",
    "confidence": 2,
    "category": "Local Networking",
    "broader": [
      11,
      23,
      30,
      31,
      32,
      38,
      49,
      51
    ],
    "narrower": [
      54,
      55,
      56,
      57,
      100,
      120,
      121
    ]
  },
  {
    "id": 53,
    "name": "Main Gateways",
    "confidence": 2,
    "category": "Local Networking",
    "broader": [
      14,
      15,
      37,
      41,
      66,
      92,
      95
    ],
    "narrower": [
      69,
      98,
      103,
      110,
      112
    ]
  },
  {
    "id": 54,
    "name": "Road Crossing",
    "confidence": 0,
    "category": "Local Networking",
    "broader": [
      23,
      32,
      50,
      52
    ],
    "narrower": [
      55,
      61,
      92,
      93,
      103,
      174,
      244
    ]
  },
  {
    "id": 55,
    "name": "Raised Walk",
    "confidence": 1,
    "category": "Local Networking",
    "broader": [
      23,
      36,
      52,
      54
    ],
    "narrower": [
      93,
      100,
      121,
      125,
      243
    ]
  },
  {
    "id": 56,
    "name": "Bike Paths and Racks",
    "confidence": 1,
    "category": "Local Networking",
    "broader": [
      11,
      49,
      52,
      73
    ],
    "narrower": [
      57,
      59,
      110,
      119,
      173
    ]
  },
  {
    "id": 57,
    "name": "Children in the City",
    "confidence": 0,
    "category": "Local Networking",
    "broader": [
      18,
      23,
      26,
      31,
      49,
      51,
      52,
      56
    ],
    "narrower": [
      40,
      41,
      43,
      68,
      70,
      72,
      73,
      74,
      84,
      85,
      86,
      164
    ]
  },
  {
    "id": 58,
    "name": "Carnival",
    "confidence": 0,
    "category": "Community Recreation",
    "broader": [
      10,
      31,
      33
    ],
    "narrower": [
      61,
      63,
      69,
      93,
      100,
      244
    ]
  },
  {
    "id": 59,
    "name": "Quiet Backs",
    "confidence": 1,
    "category": "Community Recreation",
    "broader": [
      9,
      15,
      28,
      41,
      43,
      56,
      70
    ],
    "narrower": [
      24,
      60,
      64,
      71,
      171,
      173
    ]
  },
  {
    "id": 60,
    "name": "Accessible Green",
    "confidence": 2,
    "category": "Community Recreation",
    "broader": [
      13,
      14,
      15,
      41,
      59,
      85,
      114
    ],
    "narrower": [
      66,
      67,
      69,
      70,
      72,
      74,
      94,
      106,
      171,
      173
    ]
  },
  {
    "id": 61,
    "name": "Small Public Squares",
    "confidence": 2,
    "category": "Community Recreation",
    "broader": [
      14,
      29,
      30,
      31,
      41,
      44,
      54,
      58
    ],
    "narrower": [
      62,
      63,
      69,
      88,
      93,
      94,
      106,
      114,
      122,
      123,
      124,
      125,
      126,
      164
    ]
  },
  {
    "id": 62,
    "name": "High Places",
    "confidence": 1,
    "category": "Community Recreation",
    "broader": [
      12,
      21,
      61,
      66,
      126
    ],
    "narrower": [
      125,
      134,
      158
    ]
  },
  {
    "id": 63,
    "name": "Dancing in the Street",
    "confidence": 1,
    "category": "Community Recreation",
    "broader": [
      10,
      31,
      33,
      58,
      61,
      91,
      126
    ],
    "narrower": [
      69,
      93,
      124,
      244
    ]
  },
  {
    "id": 64,
    "name": "Pools and Streams",
    "confidence": 1,
    "category": "Community Recreation",
    "broader": [
      13,
      15,
      24,
      25,
      59,
      100,
      126
    ],
    "narrower": [
      31,
      66,
      71,
      119
    ]
  },
  {
    "id": 65,
    "name": "Birth Places",
    "confidence": 0,
    "category": "Community Recreation",
    "broader": [
      12,
      14,
      26,
      30
    ],
    "narrower": [
      95,
      111,
      129,
      136,
      139,
      173
    ]
  },
  {
    "id": 66,
    "name": "Holy Ground",
    "confidence": 1,
    "category": "Community Recreation",
    "broader": [
      24,
      26,
      60,
      64
    ],
    "narrower": [
      53,
      62,
      70,
      134,
      171
    ]
  },
  {
    "id": 67,
    "name": "Common Land",
    "confidence": 2,
    "category": "Local Recreation",
    "broader": [
      37,
      38,
      39,
      41,
      51,
      60,
      98
    ],
    "narrower": [
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      105,
      106,
      114,
      126,
      170,
      175,
      177
    ]
  },
  {
    "id": 68,
    "name": "Connected Play",
    "confidence": 1,
    "category": "Local Recreation",
    "broader": [
      35,
      39,
      57,
      67
    ],
    "narrower": [
      37,
      51,
      71,
      73,
      74,
      86,
      137
    ]
  },
  {
    "id": 69,
    "name": "Public Outdoor Room",
    "confidence": 2,
    "category": "Local Recreation",
    "broader": [
      15,
      45,
      53,
      58,
      60,
      61,
      63,
      67,
      71,
      92,
      100,
      120,
      126
    ],
    "narrower": [
      94,
      115,
      119,
      121,
      124,
      125,
      129,
      160,
      163,
      226,
      241,
      244
    ]
  },
  {
    "id": 70,
    "name": "Grave Sites",
    "confidence": 1,
    "category": "Local Recreation",
    "broader": [
      14,
      15,
      26,
      57,
      60,
      66,
      67
    ],
    "narrower": [
      59,
      171,
      241
    ]
  },
  {
    "id": 71,
    "name": "Still Water",
    "confidence": 1,
    "category": "Local Recreation",
    "broader": [
      13,
      25,
      28,
      37,
      41,
      47,
      59,
      64,
      67,
      68,
      72,
      126,
      144,
      150,
      172
    ],
    "narrower": [
      69,
      105,
      174,
      243
    ]
  },
  {
    "id": 72,
    "name": "Local Sports",
    "confidence": 1,
    "category": "Local Recreation",
    "broader": [
      15,
      41,
      47,
      57,
      60,
      67,
      84
    ],
    "narrower": [
      71,
      95,
      101,
      144,
      165,
      241,
      243
    ]
  },
  {
    "id": 73,
    "name": "Adventure Playground",
    "confidence": 0,
    "category": "Local Recreation",
    "broader": [
      15,
      57,
      67,
      68,
      86
    ],
    "narrower": [
      56,
      161,
      172,
      173,
      203,
      243
    ]
  },
  {
    "id": 74,
    "name": "Animals",
    "confidence": 0,
    "category": "Local Recreation",
    "broader": [
      51,
      57,
      60,
      67,
      68,
      79
    ],
    "narrower": [
      86,
      178
    ]
  },
  {
    "id": 75,
    "name": "The Family",
    "confidence": 1,
    "category": "Social Institutions — Families",
    "broader": [
      26,
      35,
      37,
      38,
      39,
      40,
      48,
      86
    ],
    "narrower": [
      76,
      77,
      78,
      79,
      95,
      107,
      129,
      136,
      141,
      147,
      153,
      154,
      155,
      156
    ]
  },
  {
    "id": 76,
    "name": "House for a Small Family",
    "confidence": 1,
    "category": "Social Institutions — Families",
    "broader": [
      35,
      37,
      38,
      75
    ],
    "narrower": [
      78,
      79,
      107,
      129,
      136,
      137,
      141,
      143,
      145,
      154,
      158
    ]
  },
  {
    "id": 77,
    "name": "House for a Couple",
    "confidence": 1,
    "category": "Social Institutions — Families",
    "broader": [
      35,
      37,
      38,
      75
    ],
    "narrower": [
      78,
      79,
      107,
      136,
      141,
      158
    ]
  },
  {
    "id": 78,
    "name": "House for One Person",
    "confidence": 1,
    "category": "Social Institutions — Families",
    "broader": [
      35,
      37,
      38,
      75,
      76,
      77
    ],
    "narrower": [
      79,
      107,
      139,
      144,
      154,
      155,
      158,
      180,
      183,
      188,
      189
    ]
  },
  {
    "id": 79,
    "name": "Your Own Home",
    "confidence": 2,
    "category": "Social Institutions — Families",
    "broader": [
      26,
      37,
      38,
      39,
      47,
      48,
      75,
      76,
      77,
      78,
      86
    ],
    "narrower": [
      74,
      95,
      111,
      157
    ]
  },
  {
    "id": 80,
    "name": "Self-Governing Workshops and Offices",
    "confidence": 2,
    "category": "Social Institutions — Workgroups",
    "broader": [
      9,
      41,
      42,
      85
    ],
    "narrower": [
      81,
      82,
      83,
      95,
      107,
      145,
      146,
      147,
      148,
      149,
      153,
      158
    ]
  },
  {
    "id": 81,
    "name": "Small Services Without Red Tape",
    "confidence": 1,
    "category": "Social Institutions — Workgroups",
    "broader": [
      41,
      43,
      44,
      47,
      80,
      84
    ],
    "narrower": [
      45,
      82,
      95,
      101,
      102,
      107,
      146,
      148,
      149,
      150,
      153,
      158
    ]
  },
  {
    "id": 82,
    "name": "Office Connections",
    "confidence": 1,
    "category": "Social Institutions — Workgroups",
    "broader": [
      21,
      41,
      80,
      81,
      148
    ],
    "narrower": [
      107,
      146,
      150
    ]
  },
  {
    "id": 83,
    "name": "Master and Apprentices",
    "confidence": 1,
    "category": "Social Institutions — Workgroups",
    "broader": [
      18,
      26,
      43,
      80
    ],
    "narrower": [
      84,
      107,
      129,
      147,
      148,
      151,
      152,
      183
    ]
  },
  {
    "id": 84,
    "name": "Teenage Society",
    "confidence": 0,
    "category": "Social Institutions — Workgroups",
    "broader": [
      13,
      18,
      26,
      30,
      57,
      83
    ],
    "narrower": [
      72,
      81,
      95,
      147,
      157
    ]
  },
  {
    "id": 85,
    "name": "Shopfront Schools",
    "confidence": 0,
    "category": "Social Institutions — Workgroups",
    "broader": [
      18,
      26,
      30,
      57,
      86
    ],
    "narrower": [
      60,
      80,
      95,
      100,
      165
    ]
  },
  {
    "id": 86,
    "name": "Children's Home",
    "confidence": 1,
    "category": "Social Institutions — Workgroups",
    "broader": [
      18,
      26,
      40,
      57,
      68,
      74
    ],
    "narrower": [
      73,
      75,
      79,
      85,
      95,
      101,
      129,
      203
    ]
  },
  {
    "id": 87,
    "name": "Individually Owned Shops",
    "confidence": 2,
    "category": "Social Institutions — Local Gathering",
    "broader": [
      30,
      32,
      45,
      46,
      88,
      89,
      93,
      97
    ],
    "narrower": [
      95,
      107,
      145,
      165,
      191,
      197,
      200
    ]
  },
  {
    "id": 88,
    "name": "Street Cafe",
    "confidence": 2,
    "category": "Social Institutions — Local Gathering",
    "broader": [
      14,
      30,
      33,
      41,
      61,
      123,
      124
    ],
    "narrower": [
      87,
      94,
      95,
      125,
      150,
      165,
      243,
      244,
      251
    ]
  },
  {
    "id": 89,
    "name": "Corner Grocery",
    "confidence": 1,
    "category": "Social Institutions — Local Gathering",
    "broader": [
      14,
      19,
      46
    ],
    "narrower": [
      87,
      95,
      110,
      165,
      191,
      197,
      200
    ]
  },
  {
    "id": 90,
    "name": "Beer Hall",
    "confidence": 0,
    "category": "Social Institutions — Local Gathering",
    "broader": [
      15,
      30,
      31,
      33,
      91
    ],
    "narrower": [
      95,
      179,
      181,
      190
    ]
  },
  {
    "id": 91,
    "name": "Traveler's Inn",
    "confidence": 1,
    "category": "Social Institutions — Local Gathering",
    "broader": [
      10,
      30,
      31,
      33,
      41
    ],
    "narrower": [
      63,
      90,
      94,
      95,
      129,
      147,
      149,
      186
    ]
  },
  {
    "id": 92,
    "name": "Bus Stop",
    "confidence": 1,
    "category": "Social Institutions — Local Gathering",
    "broader": [
      20,
      34,
      54,
      124
    ],
    "narrower": [
      53,
      69,
      93,
      121,
      150,
      241
    ]
  },
  {
    "id": 93,
    "name": "Food Stands",
    "confidence": 1,
    "category": "Social Institutions — Local Gathering",
    "broader": [
      30,
      41,
      54,
      55,
      58,
      61,
      63,
      92
    ],
    "narrower": [
      87,
      124,
      244
    ]
  },
  {
    "id": 94,
    "name": "Sleeping in Public",
    "confidence": 0,
    "category": "Social Institutions — Local Gathering",
    "broader": [
      34,
      60,
      61,
      69,
      88,
      91,
      100,
      101,
      150
    ],
    "narrower": [
      160,
      188,
      241
    ]
  },
  {
    "id": 95,
    "name": "Building Complex",
    "confidence": 2,
    "category": "Group of Buildings",
    "broader": [
      21,
      38,
      43,
      65,
      72,
      75,
      79,
      80,
      81,
      84,
      85,
      86,
      87,
      88,
      89,
      90,
      91,
      109,
      110,
      119
    ],
    "narrower": [
      53,
      96,
      97,
      98,
      99,
      100,
      101,
      104,
      105,
      107,
      108,
      111,
      116,
      120,
      122,
      145,
      205
    ]
  },
  {
    "id": 96,
    "name": "Number of Stories",
    "confidence": 1,
    "category": "Group of Buildings",
    "broader": [
      21,
      95
    ],
    "narrower": [
      98,
      99,
      104,
      105,
      116,
      117,
      118,
      127,
      171,
      205,
      213
    ]
  },
  {
    "id": 97,
    "name": "Shielded Parking",
    "confidence": 1,
    "category": "Group of Buildings",
    "broader": [
      11,
      13,
      15,
      17,
      22,
      32,
      95
    ],
    "narrower": [
      39,
      48,
      87,
      98,
      102,
      103,
      110,
      135,
      158,
      166,
      205,
      244
    ]
  },
  {
    "id": 98,
    "name": "Circulation Realms",
    "confidence": 2,
    "category": "Group of Buildings",
    "broader": [
      37,
      53,
      95,
      96,
      97
    ],
    "narrower": [
      67,
      99,
      100,
      101,
      102,
      103,
      104,
      110,
      114,
      115,
      119,
      120,
      132
    ]
  },
  {
    "id": 99,
    "name": "Main Building",
    "confidence": 1,
    "category": "Group of Buildings",
    "broader": [
      95,
      96,
      98
    ],
    "narrower": [
      116,
      129,
      205
    ]
  },
  {
    "id": 100,
    "name": "Pedestrian Street",
    "confidence": 2,
    "category": "Group of Buildings",
    "broader": [
      31,
      32,
      36,
      38,
      39,
      43,
      46,
      52,
      55,
      58,
      85,
      95,
      98
    ],
    "narrower": [
      30,
      64,
      69,
      94,
      101,
      102,
      119,
      121,
      123,
      124,
      140,
      158,
      164,
      165,
      166,
      167,
      243
    ]
  },
  {
    "id": 101,
    "name": "Building Thoroughfare",
    "confidence": 0,
    "category": "Group of Buildings",
    "broader": [
      46,
      72,
      81,
      86,
      95,
      98,
      100
    ],
    "narrower": [
      94,
      102,
      123,
      124,
      132,
      135,
      149,
      158,
      164,
      165,
      180,
      190,
      193,
      194,
      237
    ]
  },
  {
    "id": 102,
    "name": "Family of Entrances",
    "confidence": 1,
    "category": "Group of Buildings",
    "broader": [
      81,
      97,
      98,
      100,
      101,
      120,
      158
    ],
    "narrower": [
      110,
      112,
      125,
      130,
      149,
      224
    ]
  },
  {
    "id": 103,
    "name": "Small Parking Lots",
    "confidence": 1,
    "category": "Group of Buildings",
    "broader": [
      15,
      22,
      25,
      32,
      37,
      38,
      41,
      49,
      51,
      53,
      54,
      97,
      98
    ],
    "narrower": [
      106,
      171,
      173,
      244
    ]
  },
  {
    "id": 104,
    "name": "Site Repair",
    "confidence": 2,
    "category": "Siting the Buildings",
    "broader": [
      95,
      96,
      98
    ],
    "narrower": [
      105,
      106,
      107,
      109,
      110,
      111,
      114,
      169,
      171,
      172,
      214
    ]
  },
  {
    "id": 105,
    "name": "South Facing Outdoors",
    "confidence": 2,
    "category": "Siting the Buildings",
    "broader": [
      67,
      71,
      95,
      96,
      104
    ],
    "narrower": [
      106,
      107,
      110,
      111,
      114,
      128,
      161,
      162
    ]
  },
  {
    "id": 106,
    "name": "Positive Outdoor Space",
    "confidence": 2,
    "category": "Siting the Buildings",
    "broader": [
      42,
      60,
      61,
      67,
      103,
      104,
      105,
      109,
      191
    ],
    "narrower": [
      107,
      108,
      114,
      115,
      118,
      120,
      121,
      122,
      125,
      159,
      160,
      163,
      171,
      172,
      173,
      174,
      243
    ]
  },
  {
    "id": 107,
    "name": "Wings of Light",
    "confidence": 2,
    "category": "Siting the Buildings",
    "broader": [
      75,
      76,
      77,
      78,
      80,
      81,
      82,
      83,
      87,
      95,
      104,
      105,
      106
    ],
    "narrower": [
      108,
      109,
      110,
      116,
      117,
      118,
      119,
      120,
      122,
      127,
      132,
      159,
      160,
      205
    ]
  },
  {
    "id": 108,
    "name": "Connected Buildings",
    "confidence": 1,
    "category": "Siting the Buildings",
    "broader": [
      95,
      106,
      107
    ],
    "narrower": [
      115,
      119,
      163
    ]
  },
  {
    "id": 109,
    "name": "Long Thin House",
    "confidence": 1,
    "category": "Siting the Buildings",
    "broader": [
      38,
      104,
      107
    ],
    "narrower": [
      95,
      106,
      116,
      127,
      129,
      159
    ]
  },
  {
    "id": 110,
    "name": "Main Entrance",
    "confidence": 2,
    "category": "Building Layout",
    "broader": [
      53,
      56,
      89,
      97,
      98,
      102,
      104,
      105,
      107,
      111,
      120,
      242
    ],
    "narrower": [
      95,
      112,
      113,
      125,
      127,
      130,
      133,
      224,
      249
    ]
  },
  {
    "id": 111,
    "name": "Half-Hidden Garden",
    "confidence": 1,
    "category": "Building Layout",
    "broader": [
      37,
      38,
      41,
      65,
      79,
      95,
      104,
      105,
      114
    ],
    "narrower": [
      110,
      112,
      115,
      118,
      140,
      163,
      170,
      172,
      173,
      177,
      243
    ]
  },
  {
    "id": 112,
    "name": "Entrance Transition",
    "confidence": 2,
    "category": "Building Layout",
    "broader": [
      53,
      102,
      110,
      111,
      153
    ],
    "narrower": [
      113,
      127,
      130,
      134,
      135,
      173,
      174
    ]
  },
  {
    "id": 113,
    "name": "Car Connection",
    "confidence": 0,
    "category": "Building Layout",
    "broader": [
      49,
      110,
      112
    ],
    "narrower": [
      119,
      120,
      127,
      129,
      130,
      162,
      163,
      205,
      245
    ]
  },
  {
    "id": 114,
    "name": "Hierarchy of Open Space",
    "confidence": 1,
    "category": "Building Layout",
    "broader": [
      61,
      67,
      98,
      104,
      105,
      106,
      173
    ],
    "narrower": [
      7,
      49,
      51,
      60,
      111,
      115,
      124,
      140,
      176,
      243
    ]
  },
  {
    "id": 115,
    "name": "Courtyards Which Live",
    "confidence": 2,
    "category": "Building Layout",
    "broader": [
      41,
      69,
      98,
      106,
      108,
      111,
      114
    ],
    "narrower": [
      119,
      126,
      134,
      161,
      163,
      166,
      167,
      173,
      209
    ]
  },
  {
    "id": 116,
    "name": "Cascade of Roofs",
    "confidence": 1,
    "category": "Building Layout",
    "broader": [
      95,
      96,
      99,
      107,
      109
    ],
    "narrower": [
      117,
      118,
      119,
      129,
      159,
      190,
      205,
      209,
      211
    ]
  },
  {
    "id": 117,
    "name": "Sheltering Roof",
    "confidence": 2,
    "category": "Building Layout",
    "broader": [
      96,
      107,
      116
    ],
    "narrower": [
      118,
      119,
      145,
      166,
      209,
      220,
      231
    ]
  },
  {
    "id": 118,
    "name": "Roof Garden",
    "confidence": 1,
    "category": "Building Layout",
    "broader": [
      39,
      96,
      106,
      107,
      111,
      116,
      117,
      158
    ],
    "narrower": [
      140,
      161,
      163,
      166,
      167,
      177,
      209,
      220,
      232,
      244,
      245,
      246
    ]
  },
  {
    "id": 119,
    "name": "Arcades",
    "confidence": 2,
    "category": "Between the Buildings",
    "broader": [
      34,
      56,
      64,
      69,
      98,
      100,
      107,
      108,
      113,
      115,
      116,
      117,
      121,
      124,
      129
    ],
    "narrower": [
      95,
      120,
      122,
      160,
      166,
      167,
      168,
      190,
      193,
      205,
      211,
      224,
      226,
      227,
      242,
      244
    ]
  },
  {
    "id": 120,
    "name": "Paths and Goals",
    "confidence": 1,
    "category": "Between the Buildings",
    "broader": [
      30,
      36,
      52,
      95,
      98,
      106,
      107,
      113,
      119,
      124,
      170
    ],
    "narrower": [
      69,
      102,
      110,
      121,
      126,
      134,
      171,
      174,
      241,
      245,
      247
    ]
  },
  {
    "id": 121,
    "name": "Path Shape",
    "confidence": 1,
    "category": "Between the Buildings",
    "broader": [
      31,
      32,
      36,
      52,
      55,
      69,
      92,
      100,
      106,
      120,
      165
    ],
    "narrower": [
      119,
      122,
      123,
      124,
      125,
      126,
      164,
      241,
      243,
      247
    ]
  },
  {
    "id": 122,
    "name": "Building Fronts",
    "confidence": 1,
    "category": "Between the Buildings",
    "broader": [
      42,
      45,
      61,
      95,
      106,
      107,
      119,
      121,
      124
    ],
    "narrower": [
      125,
      140,
      158,
      160,
      164,
      165,
      166,
      242
    ]
  },
  {
    "id": 123,
    "name": "Pedestrian Density",
    "confidence": 1,
    "category": "Between the Buildings",
    "broader": [
      29,
      31,
      36,
      44,
      61,
      100,
      101,
      121
    ],
    "narrower": [
      88,
      124,
      125,
      140,
      160,
      164,
      165,
      166
    ]
  },
  {
    "id": 124,
    "name": "Activity Pockets",
    "confidence": 2,
    "category": "Between the Buildings",
    "broader": [
      31,
      61,
      63,
      69,
      93,
      100,
      101,
      114,
      121,
      123
    ],
    "narrower": [
      88,
      92,
      119,
      120,
      122,
      126,
      150,
      163,
      174,
      241,
      243
    ]
  },
  {
    "id": 125,
    "name": "Stair Seats",
    "confidence": 1,
    "category": "Between the Buildings",
    "broader": [
      55,
      61,
      62,
      69,
      88,
      102,
      106,
      110,
      121,
      122,
      123,
      133,
      158,
      160,
      195
    ],
    "narrower": [
      126,
      168,
      241,
      245,
      248
    ]
  },
  {
    "id": 126,
    "name": "Something Roughly in the Middle",
    "confidence": 0,
    "category": "Between the Buildings",
    "broader": [
      61,
      67,
      115,
      120,
      121,
      124,
      125
    ],
    "narrower": [
      62,
      63,
      64,
      69,
      71,
      171,
      243
    ]
  },
  {
    "id": 127,
    "name": "Intimacy Gradient",
    "confidence": 2,
    "category": "Light and Space",
    "broader": [
      96,
      107,
      109,
      110,
      112,
      113
    ],
    "narrower": [
      128,
      129,
      130,
      131,
      136,
      138,
      141,
      142,
      144,
      146,
      149,
      152,
      185,
      233
    ]
  },
  {
    "id": 128,
    "name": "Indoor Sunlight",
    "confidence": 1,
    "category": "Light and Space",
    "broader": [
      105,
      127
    ],
    "narrower": [
      129,
      138,
      157,
      161,
      162,
      163,
      183,
      199,
      236
    ]
  },
  {
    "id": 129,
    "name": "Common Areas at the Heart",
    "confidence": 2,
    "category": "Light and Space",
    "broader": [
      65,
      69,
      75,
      76,
      83,
      86,
      91,
      99,
      109,
      113,
      116,
      127,
      128,
      148,
      185
    ],
    "narrower": [
      119,
      131,
      132,
      137,
      139,
      140,
      141,
      142,
      144,
      146,
      147,
      159,
      163,
      179,
      181,
      191,
      252
    ]
  },
  {
    "id": 130,
    "name": "Entrance Room",
    "confidence": 2,
    "category": "Light and Space",
    "broader": [
      102,
      110,
      112,
      113,
      127,
      131,
      140,
      168
    ],
    "narrower": [
      134,
      135,
      142,
      149,
      159,
      166,
      180,
      191,
      194,
      201,
      202,
      237,
      242,
      252
    ]
  },
  {
    "id": 131,
    "name": "The Flow Through Rooms",
    "confidence": 0,
    "category": "Light and Space",
    "broader": [
      127,
      129
    ],
    "narrower": [
      130,
      132,
      133,
      134,
      135,
      159,
      193,
      194,
      196,
      224
    ]
  },
  {
    "id": 132,
    "name": "Short Passages",
    "confidence": 1,
    "category": "Light and Space",
    "broader": [
      98,
      101,
      107,
      129,
      131,
      137
    ],
    "narrower": [
      133,
      134,
      135,
      159,
      163,
      166,
      179,
      180,
      191,
      194,
      197,
      198,
      222,
      237
    ]
  },
  {
    "id": 133,
    "name": "Staircase as a Stage",
    "confidence": 0,
    "category": "Light and Space",
    "broader": [
      110,
      131,
      132
    ],
    "narrower": [
      125,
      134,
      135,
      191,
      195,
      228
    ]
  },
  {
    "id": 134,
    "name": "Zen View",
    "confidence": 1,
    "category": "Light and Space",
    "broader": [
      62,
      66,
      112,
      115,
      120,
      130,
      131,
      132,
      133,
      142,
      173
    ],
    "narrower": [
      24,
      135,
      180,
      221,
      222
    ]
  },
  {
    "id": 135,
    "name": "Tapestry of Light and Dark",
    "confidence": 1,
    "category": "Light and Space",
    "broader": [
      97,
      101,
      112,
      130,
      131,
      132,
      133,
      134,
      149
    ],
    "narrower": [
      180,
      194,
      196,
      237,
      250,
      252
    ]
  },
  {
    "id": 136,
    "name": "Couple's Realm",
    "confidence": 1,
    "category": "Private Rooms",
    "broader": [
      65,
      75,
      76,
      77,
      127,
      142
    ],
    "narrower": [
      137,
      138,
      143,
      144,
      159,
      185,
      186,
      187,
      189,
      191,
      198,
      224
    ]
  },
  {
    "id": 137,
    "name": "Children's Realm",
    "confidence": 1,
    "category": "Private Rooms",
    "broader": [
      68,
      76,
      129,
      136
    ],
    "narrower": [
      132,
      138,
      139,
      143,
      144,
      157,
      163,
      186,
      203
    ]
  },
  {
    "id": 138,
    "name": "Sleeping to the East",
    "confidence": 1,
    "category": "Private Rooms",
    "broader": [
      127,
      128,
      136,
      137
    ],
    "narrower": [
      143,
      144,
      180,
      186,
      187,
      188,
      221,
      238
    ]
  },
  {
    "id": 139,
    "name": "Farmhouse Kitchen",
    "confidence": 2,
    "category": "Private Rooms",
    "broader": [
      65,
      78,
      129,
      137,
      147
    ],
    "narrower": [
      142,
      159,
      163,
      179,
      182,
      184,
      191,
      199,
      200,
      201
    ]
  },
  {
    "id": 140,
    "name": "Private Terrace on the Street",
    "confidence": 2,
    "category": "Private Rooms",
    "broader": [
      51,
      100,
      111,
      114,
      118,
      122,
      123,
      129,
      142,
      155,
      156,
      161,
      166
    ],
    "narrower": [
      130,
      163,
      168,
      169,
      173,
      193,
      241,
      243,
      244,
      247
    ]
  },
  {
    "id": 141,
    "name": "A Room of One's Own",
    "confidence": 2,
    "category": "Private Rooms",
    "broader": [
      27,
      75,
      76,
      77,
      127,
      129,
      142
    ],
    "narrower": [
      154,
      155,
      156,
      157,
      159,
      179,
      183,
      188,
      189,
      191,
      253
    ]
  },
  {
    "id": 142,
    "name": "Sequence of Sitting Spaces",
    "confidence": 1,
    "category": "Private Rooms",
    "broader": [
      127,
      129,
      130,
      139
    ],
    "narrower": [
      134,
      136,
      140,
      141,
      146,
      150,
      152,
      163,
      179,
      180,
      181,
      185,
      191,
      194,
      196,
      202,
      241,
      251
    ]
  },
  {
    "id": 143,
    "name": "Bed Cluster",
    "confidence": 1,
    "category": "Private Rooms",
    "broader": [
      76,
      136,
      137,
      138
    ],
    "narrower": [
      144,
      159,
      186,
      188,
      189,
      191,
      198,
      203
    ]
  },
  {
    "id": 144,
    "name": "Bathing Room",
    "confidence": 1,
    "category": "Private Rooms",
    "broader": [
      72,
      78,
      127,
      129,
      136,
      137,
      138,
      143,
      177
    ],
    "narrower": [
      71,
      159,
      173,
      178,
      189,
      191,
      238
    ]
  },
  {
    "id": 145,
    "name": "Bulk Storage",
    "confidence": 0,
    "category": "Private Rooms",
    "broader": [
      76,
      80,
      87,
      95,
      117,
      175
    ],
    "narrower": [
      153,
      162,
      169,
      190,
      215
    ]
  },
  {
    "id": 146,
    "name": "Flexible Office Space",
    "confidence": 0,
    "category": "Public Rooms",
    "broader": [
      80,
      81,
      82,
      127,
      129,
      142
    ],
    "narrower": [
      147,
      148,
      149,
      151,
      152,
      153,
      159,
      179,
      183,
      190,
      226,
      252
    ]
  },
  {
    "id": 147,
    "name": "Communal Eating",
    "confidence": 1,
    "category": "Public Rooms",
    "broader": [
      41,
      75,
      80,
      83,
      84,
      91,
      129,
      146
    ],
    "narrower": [
      139,
      148,
      151,
      182
    ]
  },
  {
    "id": 148,
    "name": "Small Work Groups",
    "confidence": 2,
    "category": "Public Rooms",
    "broader": [
      80,
      81,
      83,
      146,
      147
    ],
    "narrower": [
      82,
      129,
      151,
      152,
      158,
      183
    ]
  },
  {
    "id": 149,
    "name": "Reception Welcomes You",
    "confidence": 0,
    "category": "Public Rooms",
    "broader": [
      80,
      81,
      91,
      101,
      102,
      127,
      130,
      146
    ],
    "narrower": [
      135,
      150,
      159,
      179,
      180,
      181,
      183,
      191
    ]
  },
  {
    "id": 150,
    "name": "A Place to Wait",
    "confidence": 1,
    "category": "Public Rooms",
    "broader": [
      34,
      47,
      81,
      82,
      88,
      92,
      124,
      142,
      149
    ],
    "narrower": [
      71,
      94,
      159,
      164,
      165,
      176,
      179,
      180,
      191
    ]
  },
  {
    "id": 151,
    "name": "Small Meeting Rooms",
    "confidence": 1,
    "category": "Public Rooms",
    "broader": [
      43,
      44,
      83,
      146,
      147,
      148
    ],
    "narrower": [
      159,
      179,
      185,
      191,
      251,
      252
    ]
  },
  {
    "id": 152,
    "name": "Half-Private Office",
    "confidence": 0,
    "category": "Public Rooms",
    "broader": [
      83,
      127,
      142,
      146,
      148
    ],
    "narrower": [
      159,
      183,
      185,
      191,
      192,
      193
    ]
  },
  {
    "id": 153,
    "name": "Rooms to Rent",
    "confidence": 0,
    "category": "Outbuildings",
    "broader": [
      26,
      45,
      75,
      80,
      81,
      145,
      146
    ],
    "narrower": [
      112,
      154,
      155,
      157,
      158,
      159,
      191
    ]
  },
  {
    "id": 154,
    "name": "Teenager's Cottage",
    "confidence": 1,
    "category": "Outbuildings",
    "broader": [
      26,
      75,
      76,
      78,
      141,
      153
    ],
    "narrower": [
      155,
      157,
      158,
      185,
      188,
      191,
      205
    ]
  },
  {
    "id": 155,
    "name": "Old Age Cottage",
    "confidence": 2,
    "category": "Outbuildings",
    "broader": [
      26,
      40,
      75,
      78,
      141,
      153,
      154
    ],
    "narrower": [
      140,
      156,
      164,
      191,
      205,
      242
    ]
  },
  {
    "id": 156,
    "name": "Settled Work",
    "confidence": 1,
    "category": "Outbuildings",
    "broader": [
      26,
      40,
      75,
      141,
      155
    ],
    "narrower": [
      140,
      157,
      158,
      165
    ]
  },
  {
    "id": 157,
    "name": "Home Workshop",
    "confidence": 0,
    "category": "Outbuildings",
    "broader": [
      9,
      18,
      27,
      37,
      79,
      84,
      128,
      137,
      141,
      153,
      154,
      156
    ],
    "narrower": [
      158,
      159,
      161,
      165,
      183,
      191,
      192
    ]
  },
  {
    "id": 158,
    "name": "Open Stairs",
    "confidence": 1,
    "category": "Outbuildings",
    "broader": [
      39,
      62,
      76,
      77,
      78,
      80,
      81,
      97,
      100,
      101,
      122,
      148,
      153,
      154,
      156,
      157
    ],
    "narrower": [
      102,
      118,
      125,
      161,
      195
    ]
  },
  {
    "id": 159,
    "name": "Light on Two Sides of Every Room",
    "confidence": 2,
    "category": "Liminal Space",
    "broader": [
      106,
      107,
      109,
      116,
      129,
      130,
      131,
      132,
      136,
      139,
      141,
      143,
      144,
      146,
      149,
      150,
      151,
      152,
      153,
      157,
      162,
      189
    ],
    "narrower": [
      160,
      180,
      192,
      209,
      221,
      223,
      238
    ]
  },
  {
    "id": 160,
    "name": "Building Edge",
    "confidence": 2,
    "category": "Liminal Space",
    "broader": [
      45,
      69,
      94,
      106,
      107,
      119,
      122,
      123,
      159
    ],
    "narrower": [
      125,
      161,
      162,
      163,
      164,
      166,
      167,
      168,
      169,
      197,
      241,
      242,
      245,
      249
    ]
  },
  {
    "id": 161,
    "name": "Sunny Place",
    "confidence": 2,
    "category": "Liminal Space",
    "broader": [
      73,
      105,
      115,
      118,
      128,
      157,
      158,
      160
    ],
    "narrower": [
      140,
      162,
      163,
      167,
      174,
      176,
      238,
      241,
      242,
      244
    ]
  },
  {
    "id": 162,
    "name": "North Face",
    "confidence": 0,
    "category": "Liminal Space",
    "broader": [
      105,
      113,
      128,
      145,
      160,
      161
    ],
    "narrower": [
      159,
      173,
      178,
      198
    ]
  },
  {
    "id": 163,
    "name": "Outdoor Room",
    "confidence": 2,
    "category": "Liminal Space",
    "broader": [
      69,
      106,
      108,
      111,
      113,
      115,
      118,
      124,
      128,
      129,
      132,
      137,
      139,
      140,
      142,
      160,
      161,
      165,
      166,
      167,
      171
    ],
    "narrower": [
      168,
      173,
      174,
      191,
      205,
      226,
      241,
      243,
      244,
      247
    ]
  },
  {
    "id": 164,
    "name": "Street Windows",
    "confidence": 1,
    "category": "Liminal Space",
    "broader": [
      51,
      57,
      61,
      100,
      101,
      121,
      122,
      123,
      150,
      155,
      160
    ],
    "narrower": [
      165,
      180,
      221,
      236,
      238,
      246
    ]
  },
  {
    "id": 165,
    "name": "Opening to the Street",
    "confidence": 1,
    "category": "Liminal Space",
    "broader": [
      43,
      44,
      45,
      46,
      47,
      72,
      85,
      87,
      88,
      89,
      100,
      101,
      122,
      123,
      150,
      156,
      157,
      164
    ],
    "narrower": [
      121,
      163,
      243
    ]
  },
  {
    "id": 166,
    "name": "Gallery Surround",
    "confidence": 1,
    "category": "Liminal Space",
    "broader": [
      97,
      100,
      115,
      117,
      118,
      119,
      122,
      123,
      130,
      132,
      160
    ],
    "narrower": [
      140,
      163,
      167,
      168,
      193,
      226,
      227,
      243,
      244
    ]
  },
  {
    "id": 167,
    "name": "Six-Foot Balcony",
    "confidence": 2,
    "category": "Liminal Space",
    "broader": [
      100,
      115,
      118,
      119,
      160,
      161,
      166
    ],
    "narrower": [
      163,
      168,
      191,
      193,
      226,
      227,
      243
    ]
  },
  {
    "id": 168,
    "name": "Connection to the Earth",
    "confidence": 2,
    "category": "Liminal Space",
    "broader": [
      119,
      125,
      140,
      160,
      163,
      166,
      167
    ],
    "narrower": [
      130,
      169,
      214,
      215,
      241,
      242,
      247,
      248,
      249
    ]
  },
  {
    "id": 169,
    "name": "Terraced Slope",
    "confidence": 1,
    "category": "Gardens",
    "broader": [
      104,
      140,
      145,
      160,
      168
    ],
    "narrower": [
      170,
      172,
      177,
      243,
      245,
      247
    ]
  },
  {
    "id": 170,
    "name": "Fruit Trees",
    "confidence": 1,
    "category": "Gardens",
    "broader": [
      51,
      67,
      111,
      169
    ],
    "narrower": [
      120,
      171,
      172,
      174,
      176,
      177,
      178
    ]
  },
  {
    "id": 171,
    "name": "Tree Places",
    "confidence": 2,
    "category": "Gardens",
    "broader": [
      59,
      60,
      66,
      70,
      96,
      103,
      104,
      106,
      120,
      126,
      170
    ],
    "narrower": [
      24,
      163,
      174,
      176,
      241,
      243
    ]
  },
  {
    "id": 172,
    "name": "Garden Growing Wild",
    "confidence": 2,
    "category": "Gardens",
    "broader": [
      73,
      104,
      106,
      111,
      169,
      170
    ],
    "narrower": [
      71,
      175,
      176,
      243,
      245
    ]
  },
  {
    "id": 173,
    "name": "Garden Wall",
    "confidence": 1,
    "category": "Gardens",
    "broader": [
      56,
      59,
      60,
      65,
      73,
      103,
      106,
      111,
      112,
      115,
      140,
      144,
      162,
      163
    ],
    "narrower": [
      114,
      134,
      174,
      193,
      245,
      249
    ]
  },
  {
    "id": 174,
    "name": "Trellised Walk",
    "confidence": 2,
    "category": "Gardens",
    "broader": [
      54,
      71,
      106,
      112,
      120,
      124,
      161,
      163,
      170,
      171,
      173,
      175
    ],
    "narrower": [
      226,
      238,
      241,
      244,
      246,
      247
    ]
  },
  {
    "id": 175,
    "name": "Greenhouse",
    "confidence": 0,
    "category": "Gardens",
    "broader": [
      37,
      41,
      67,
      172
    ],
    "narrower": [
      145,
      174,
      176,
      177,
      178,
      180,
      201
    ]
  },
  {
    "id": 176,
    "name": "Garden Seat",
    "confidence": 0,
    "category": "Gardens",
    "broader": [
      114,
      150,
      161,
      170,
      171,
      172,
      175
    ],
    "narrower": [
      24,
      238,
      241
    ]
  },
  {
    "id": 177,
    "name": "Vegetable Garden",
    "confidence": 1,
    "category": "Gardens",
    "broader": [
      39,
      40,
      67,
      111,
      118,
      169,
      170,
      175
    ],
    "narrower": [
      144,
      178
    ]
  },
  {
    "id": 178,
    "name": "Compost",
    "confidence": 1,
    "category": "Gardens",
    "broader": [
      37,
      74,
      144,
      162,
      170,
      175,
      177,
      181
    ],
    "narrower": []
  },
  {
    "id": 179,
    "name": "Alcoves",
    "confidence": 2,
    "category": "Minor Rooms",
    "broader": [
      90,
      129,
      132,
      139,
      141,
      142,
      146,
      149,
      150,
      151,
      186,
      228,
      231
    ],
    "narrower": [
      180,
      183,
      190,
      191,
      193,
      197,
      202,
      211,
      226,
      252
    ]
  },
  {
    "id": 180,
    "name": "Window Place",
    "confidence": 2,
    "category": "Minor Rooms",
    "broader": [
      78,
      101,
      130,
      132,
      134,
      135,
      138,
      142,
      149,
      150,
      159,
      164,
      175,
      179,
      181,
      185
    ],
    "narrower": [
      197,
      202,
      211,
      221,
      222,
      223,
      231,
      236,
      244,
      249
    ]
  },
  {
    "id": 181,
    "name": "The Fire",
    "confidence": 1,
    "category": "Minor Rooms",
    "broader": [
      90,
      129,
      142,
      149
    ],
    "narrower": [
      178,
      180,
      185
    ]
  },
  {
    "id": 182,
    "name": "Eating Atmosphere",
    "confidence": 0,
    "category": "Minor Rooms",
    "broader": [
      139,
      147
    ],
    "narrower": [
      200,
      201,
      202,
      250,
      251,
      252
    ]
  },
  {
    "id": 183,
    "name": "Workspace Enclosure",
    "confidence": 2,
    "category": "Minor Rooms",
    "broader": [
      78,
      83,
      128,
      141,
      146,
      148,
      149,
      152,
      157,
      179
    ],
    "narrower": [
      185,
      191,
      192,
      193,
      197,
      198,
      200,
      201,
      252
    ]
  },
  {
    "id": 184,
    "name": "Cooking Layout",
    "confidence": 1,
    "category": "Minor Rooms",
    "broader": [
      139
    ],
    "narrower": [
      197,
      199,
      200
    ]
  },
  {
    "id": 185,
    "name": "Sitting Circle",
    "confidence": 1,
    "category": "Minor Rooms",
    "broader": [
      127,
      136,
      142,
      151,
      152,
      154,
      181,
      183
    ],
    "narrower": [
      129,
      180,
      191,
      193,
      251,
      252
    ]
  },
  {
    "id": 186,
    "name": "Communal Sleeping",
    "confidence": 0,
    "category": "Minor Rooms",
    "broader": [
      91,
      136,
      137,
      138,
      143
    ],
    "narrower": [
      179,
      187,
      188,
      189
    ]
  },
  {
    "id": 187,
    "name": "Marriage Bed",
    "confidence": 0,
    "category": "Minor Rooms",
    "broader": [
      26,
      136,
      138,
      186
    ],
    "narrower": [
      188,
      189,
      190,
      191,
      249
    ]
  },
  {
    "id": 188,
    "name": "Bed Alcove",
    "confidence": 2,
    "category": "Minor Rooms",
    "broader": [
      78,
      94,
      138,
      141,
      143,
      154,
      186,
      187
    ],
    "narrower": [
      189,
      190,
      191,
      193,
      197,
      200,
      221
    ]
  },
  {
    "id": 189,
    "name": "Dressing Rooms",
    "confidence": 1,
    "category": "Minor Rooms",
    "broader": [
      78,
      136,
      141,
      143,
      144,
      186,
      187,
      188
    ],
    "narrower": [
      159,
      191,
      197,
      198,
      200,
      201
    ]
  },
  {
    "id": 190,
    "name": "Ceiling Height Variety",
    "confidence": 2,
    "category": "Shaping the Rooms",
    "broader": [
      90,
      101,
      116,
      119,
      145,
      146,
      179,
      187,
      188,
      205
    ],
    "narrower": [
      191,
      192,
      197,
      204,
      210,
      213,
      219
    ]
  },
  {
    "id": 191,
    "name": "The Shape of Indoor Space",
    "confidence": 2,
    "category": "Shaping the Rooms",
    "broader": [
      87,
      89,
      129,
      130,
      132,
      133,
      136,
      139,
      141,
      142,
      143,
      144,
      149,
      150,
      151,
      152,
      153,
      154,
      155,
      157,
      163,
      167,
      179,
      183,
      185,
      187,
      188,
      189,
      190
    ],
    "narrower": [
      106,
      192,
      193,
      197,
      198,
      205,
      210,
      212,
      218,
      219
    ]
  },
  {
    "id": 192,
    "name": "Windows Overlooking Life",
    "confidence": 1,
    "category": "Shaping the Rooms",
    "broader": [
      152,
      157,
      159,
      183,
      190,
      191,
      199
    ],
    "narrower": [
      221,
      222,
      223,
      236,
      239
    ]
  },
  {
    "id": 193,
    "name": "Half-Open Wall",
    "confidence": 1,
    "category": "Shaping the Rooms",
    "broader": [
      101,
      119,
      131,
      140,
      152,
      166,
      167,
      173,
      179,
      183,
      185,
      188,
      191
    ],
    "narrower": [
      194,
      212,
      226,
      227,
      239,
      249
    ]
  },
  {
    "id": 194,
    "name": "Interior Windows",
    "confidence": 0,
    "category": "Shaping the Rooms",
    "broader": [
      101,
      130,
      131,
      132,
      135,
      142,
      193
    ],
    "narrower": [
      237,
      239
    ]
  },
  {
    "id": 195,
    "name": "Staircase Volume",
    "confidence": 1,
    "category": "Shaping the Rooms",
    "broader": [
      133,
      158
    ],
    "narrower": [
      125,
      203,
      212,
      228
    ]
  },
  {
    "id": 196,
    "name": "Corner Doors",
    "confidence": 1,
    "category": "Shaping the Rooms",
    "broader": [
      131,
      135,
      142
    ],
    "narrower": [
      198,
      221,
      224,
      225,
      237,
      249
    ]
  },
  {
    "id": 197,
    "name": "Thick Walls",
    "confidence": 2,
    "category": "Thick Walls",
    "broader": [
      87,
      89,
      132,
      160,
      179,
      180,
      183,
      184,
      188,
      189,
      190,
      191,
      223
    ],
    "narrower": [
      198,
      199,
      200,
      201,
      202,
      203,
      204,
      211,
      212
    ]
  },
  {
    "id": 198,
    "name": "Closets Between Rooms",
    "confidence": 1,
    "category": "Thick Walls",
    "broader": [
      132,
      136,
      143,
      162,
      183,
      189,
      191,
      196,
      197,
      204,
      228
    ],
    "narrower": []
  },
  {
    "id": 199,
    "name": "Sunny Counter",
    "confidence": 1,
    "category": "Thick Walls",
    "broader": [
      128,
      139,
      184,
      197
    ],
    "narrower": [
      192,
      200,
      211,
      250
    ]
  },
  {
    "id": 200,
    "name": "Open Shelves",
    "confidence": 1,
    "category": "Thick Walls",
    "broader": [
      87,
      89,
      139,
      182,
      183,
      184,
      188,
      189,
      197,
      199
    ],
    "narrower": [
      201,
      211
    ]
  },
  {
    "id": 201,
    "name": "Waist-High Shelf",
    "confidence": 0,
    "category": "Thick Walls",
    "broader": [
      130,
      139,
      175,
      182,
      183,
      189,
      197,
      200,
      222
    ],
    "narrower": [
      211,
      253
    ]
  },
  {
    "id": 202,
    "name": "Built-in Seats",
    "confidence": 1,
    "category": "Thick Walls",
    "broader": [
      130,
      142,
      179,
      180,
      182,
      197,
      230
    ],
    "narrower": [
      211,
      251
    ]
  },
  {
    "id": 203,
    "name": "Child Caves",
    "confidence": 0,
    "category": "Thick Walls",
    "broader": [
      73,
      86,
      137,
      143,
      195,
      197,
      228
    ],
    "narrower": [
      211,
      224
    ]
  },
  {
    "id": 204,
    "name": "Secret Place",
    "confidence": 0,
    "category": "Thick Walls",
    "broader": [
      190,
      197
    ],
    "narrower": [
      198,
      211,
      219
    ]
  },
  {
    "id": 205,
    "name": "Structure Follows Social Spaces",
    "confidence": 2,
    "category": "Emergent Structure",
    "broader": [
      95,
      96,
      97,
      99,
      107,
      113,
      116,
      119,
      154,
      155,
      163,
      191,
      219
    ],
    "narrower": [
      190,
      206,
      207,
      208,
      212
    ]
  },
  {
    "id": 206,
    "name": "Efficient Structure",
    "confidence": 1,
    "category": "Emergent Structure",
    "broader": [
      205
    ],
    "narrower": [
      207,
      208,
      209,
      210,
      212,
      213,
      215,
      216,
      217,
      218,
      219,
      220,
      225,
      227,
      228,
      229
    ]
  },
  {
    "id": 207,
    "name": "Good Materials",
    "confidence": 2,
    "category": "Emergent Structure",
    "broader": [
      205,
      206
    ],
    "narrower": [
      208,
      219,
      228,
      234,
      235,
      248,
      250
    ]
  },
  {
    "id": 208,
    "name": "Gradual Stiffening",
    "confidence": 2,
    "category": "Emergent Structure",
    "broader": [
      205,
      206,
      207,
      231
    ],
    "narrower": [
      212,
      216,
      217,
      218,
      219,
      220,
      225
    ]
  },
  {
    "id": 209,
    "name": "Roof Layout",
    "confidence": 1,
    "category": "Structural Layout",
    "broader": [
      115,
      116,
      117,
      118,
      159,
      206
    ],
    "narrower": [
      210,
      211,
      212,
      220
    ]
  },
  {
    "id": 210,
    "name": "Floor and Ceiling Layout",
    "confidence": 0,
    "category": "Structural Layout",
    "broader": [
      190,
      191,
      206,
      209
    ],
    "narrower": [
      211,
      212,
      213,
      217,
      219,
      233
    ]
  },
  {
    "id": 211,
    "name": "Thickening the Outer Walls",
    "confidence": 1,
    "category": "Structural Layout",
    "broader": [
      116,
      119,
      179,
      180,
      197,
      199,
      200,
      201,
      202,
      203,
      204,
      209,
      210
    ],
    "narrower": [
      212,
      219,
      220
    ]
  },
  {
    "id": 212,
    "name": "Columns at the Corners",
    "confidence": 2,
    "category": "Structural Layout",
    "broader": [
      46,
      191,
      193,
      195,
      197,
      205,
      206,
      208,
      209,
      210,
      211,
      231
    ],
    "narrower": [
      213,
      214,
      215,
      216,
      217,
      219,
      220,
      226
    ]
  },
  {
    "id": 213,
    "name": "Final Column Distribution",
    "confidence": 2,
    "category": "Structural Layout",
    "broader": [
      96,
      190,
      206,
      210,
      212,
      219
    ],
    "narrower": [
      214,
      216,
      218
    ]
  },
  {
    "id": 214,
    "name": "Root Foundations",
    "confidence": 0,
    "category": "Erecting the Frame",
    "broader": [
      104,
      168,
      212,
      213,
      219
    ],
    "narrower": [
      215,
      216
    ]
  },
  {
    "id": 215,
    "name": "Ground Floor Slab",
    "confidence": 0,
    "category": "Erecting the Frame",
    "broader": [
      145,
      168,
      206,
      212,
      214
    ],
    "narrower": [
      219,
      233,
      248
    ]
  },
  {
    "id": 216,
    "name": "Box Columns",
    "confidence": 2,
    "category": "Erecting the Frame",
    "broader": [
      206,
      208,
      212,
      213,
      214,
      231
    ],
    "narrower": [
      217,
      218,
      219,
      221,
      226,
      227,
      240
    ]
  },
  {
    "id": 217,
    "name": "Perimeter Beams",
    "confidence": 1,
    "category": "Erecting the Frame",
    "broader": [
      206,
      208,
      210,
      212,
      216,
      231
    ],
    "narrower": [
      219,
      221,
      227,
      240
    ]
  },
  {
    "id": 218,
    "name": "Wall Membranes",
    "confidence": 1,
    "category": "Erecting the Frame",
    "broader": [
      191,
      206,
      208,
      213,
      216,
      231,
      237,
      249
    ],
    "narrower": [
      230,
      234,
      235,
      248
    ]
  },
  {
    "id": 219,
    "name": "Floor-Ceiling Vaults",
    "confidence": 2,
    "category": "Erecting the Frame",
    "broader": [
      190,
      191,
      204,
      206,
      207,
      208,
      210,
      211,
      212,
      215,
      216,
      217,
      228,
      231
    ],
    "narrower": [
      205,
      213,
      214,
      220,
      229,
      230,
      233,
      235,
      240
    ]
  },
  {
    "id": 220,
    "name": "Roof Vaults",
    "confidence": 1,
    "category": "Erecting the Frame",
    "broader": [
      117,
      118,
      206,
      208,
      209,
      211,
      212,
      219
    ],
    "narrower": [
      231,
      232,
      234
    ]
  },
  {
    "id": 221,
    "name": "Natural Doors and Windows",
    "confidence": 2,
    "category": "Fenestration",
    "broader": [
      134,
      138,
      159,
      164,
      180,
      188,
      192,
      196,
      216,
      217
    ],
    "narrower": [
      222,
      223,
      224,
      225,
      236,
      238,
      239
    ]
  },
  {
    "id": 222,
    "name": "Low Sill",
    "confidence": 0,
    "category": "Fenestration",
    "broader": [
      132,
      134,
      180,
      192,
      221
    ],
    "narrower": [
      201,
      225,
      236,
      245
    ]
  },
  {
    "id": 223,
    "name": "Deep Reveals",
    "confidence": 0,
    "category": "Fenestration",
    "broader": [
      159,
      180,
      192,
      221
    ],
    "narrower": [
      197,
      225,
      238,
      240,
      246
    ]
  },
  {
    "id": 224,
    "name": "Low Doorway",
    "confidence": 0,
    "category": "Fenestration",
    "broader": [
      102,
      110,
      119,
      131,
      136,
      196,
      203,
      221
    ],
    "narrower": [
      225,
      237,
      249
    ]
  },
  {
    "id": 225,
    "name": "Frames as Thickened Edges",
    "confidence": 2,
    "category": "Fenestration",
    "broader": [
      196,
      206,
      208,
      221,
      222,
      223,
      224,
      231
    ],
    "narrower": [
      227,
      236,
      237,
      239,
      240,
      249
    ]
  },
  {
    "id": 226,
    "name": "Column Place",
    "confidence": 1,
    "category": "Frame Adjustments",
    "broader": [
      69,
      119,
      146,
      163,
      166,
      167,
      174,
      179,
      193,
      212,
      216
    ],
    "narrower": [
      227,
      243,
      245,
      249,
      251
    ]
  },
  {
    "id": 227,
    "name": "Column Connections",
    "confidence": 2,
    "category": "Frame Adjustments",
    "broader": [
      119,
      166,
      167,
      193,
      206,
      216,
      217,
      225,
      226
    ],
    "narrower": [
      249
    ]
  },
  {
    "id": 228,
    "name": "Stair Vault",
    "confidence": 1,
    "category": "Frame Adjustments",
    "broader": [
      133,
      195,
      206,
      207
    ],
    "narrower": [
      179,
      198,
      203,
      219,
      233,
      248
    ]
  },
  {
    "id": 229,
    "name": "Duct Space",
    "confidence": 0,
    "category": "Frame Adjustments",
    "broader": [
      206,
      219
    ],
    "narrower": [
      230,
      252
    ]
  },
  {
    "id": 230,
    "name": "Radiant Heat",
    "confidence": 1,
    "category": "Frame Adjustments",
    "broader": [
      218,
      219,
      229
    ],
    "narrower": [
      202
    ]
  },
  {
    "id": 231,
    "name": "Dormer Windows",
    "confidence": 1,
    "category": "Frame Adjustments",
    "broader": [
      117,
      180,
      220
    ],
    "narrower": [
      179,
      208,
      212,
      216,
      217,
      218,
      219,
      225,
      236,
      239
    ]
  },
  {
    "id": 232,
    "name": "Roof Caps",
    "confidence": 0,
    "category": "Frame Adjustments",
    "broader": [
      118,
      220
    ],
    "narrower": [
      249
    ]
  },
  {
    "id": 233,
    "name": "Floor Surface",
    "confidence": 2,
    "category": "Interior Details",
    "broader": [
      127,
      210,
      215,
      219,
      228
    ],
    "narrower": [
      248,
      249,
      250
    ]
  },
  {
    "id": 234,
    "name": "Lapped Outside Walls",
    "confidence": 0,
    "category": "Interior Details",
    "broader": [
      207,
      218,
      220,
      249
    ],
    "narrower": [
      240
    ]
  },
  {
    "id": 235,
    "name": "Soft Inside Walls",
    "confidence": 1,
    "category": "Interior Details",
    "broader": [
      207,
      218,
      219
    ],
    "narrower": [
      240,
      249,
      250
    ]
  },
  {
    "id": 236,
    "name": "Windows Which Open Wide",
    "confidence": 1,
    "category": "Interior Details",
    "broader": [
      128,
      164,
      180,
      192,
      221,
      222,
      225,
      231
    ],
    "narrower": [
      239
    ]
  },
  {
    "id": 237,
    "name": "Solid Doors with Glass",
    "confidence": 0,
    "category": "Interior Details",
    "broader": [
      101,
      130,
      132,
      135,
      194,
      196,
      224,
      225
    ],
    "narrower": [
      218,
      239
    ]
  },
  {
    "id": 238,
    "name": "Filtered Light",
    "confidence": 1,
    "category": "Interior Details",
    "broader": [
      138,
      144,
      159,
      161,
      164,
      174,
      176,
      221,
      223
    ],
    "narrower": [
      239,
      244,
      246,
      250
    ]
  },
  {
    "id": 239,
    "name": "Small Panes",
    "confidence": 2,
    "category": "Interior Details",
    "broader": [
      192,
      193,
      194,
      221,
      225,
      231,
      236,
      237,
      238
    ],
    "narrower": [
      240
    ]
  },
  {
    "id": 240,
    "name": "Half-Inch Trim",
    "confidence": 2,
    "category": "Interior Details",
    "broader": [
      216,
      217,
      219,
      223,
      225,
      234,
      235,
      239
    ],
    "narrower": [
      249,
      250
    ]
  },
  {
    "id": 241,
    "name": "Seat Spots",
    "confidence": 2,
    "category": "Outdoor Details",
    "broader": [
      69,
      70,
      72,
      92,
      94,
      120,
      121,
      124,
      125,
      140,
      142,
      160,
      161,
      163,
      168,
      171,
      174,
      176
    ],
    "narrower": [
      242,
      243
    ]
  },
  {
    "id": 242,
    "name": "Front Door Bench",
    "confidence": 1,
    "category": "Outdoor Details",
    "broader": [
      119,
      122,
      130,
      155,
      160,
      161,
      168,
      241
    ],
    "narrower": [
      110,
      243,
      245
    ]
  },
  {
    "id": 243,
    "name": "Sitting Wall",
    "confidence": 2,
    "category": "Outdoor Details",
    "broader": [
      51,
      55,
      71,
      72,
      73,
      88,
      100,
      106,
      111,
      114,
      121,
      124,
      126,
      140,
      163,
      165,
      166,
      167,
      169,
      171,
      172,
      226,
      241,
      242
    ],
    "narrower": [
      245,
      248,
      249
    ]
  },
  {
    "id": 244,
    "name": "Canvas Roofs",
    "confidence": 1,
    "category": "Outdoor Details",
    "broader": [
      32,
      46,
      54,
      58,
      63,
      69,
      88,
      93,
      97,
      103,
      118,
      119,
      140,
      161,
      163,
      166,
      174,
      180,
      238
    ],
    "narrower": [
      249,
      250
    ]
  },
  {
    "id": 245,
    "name": "Raised Flowers",
    "confidence": 1,
    "category": "Outdoor Details",
    "broader": [
      51,
      113,
      118,
      120,
      125,
      160,
      169,
      172,
      173,
      222,
      226,
      242,
      243
    ],
    "narrower": []
  },
  {
    "id": 246,
    "name": "Climbing Plants",
    "confidence": 0,
    "category": "Outdoor Details",
    "broader": [
      118,
      164,
      174,
      223,
      238
    ],
    "narrower": []
  },
  {
    "id": 247,
    "name": "Paving With Cracks Between the Stones",
    "confidence": 2,
    "category": "Outdoor Details",
    "broader": [
      51,
      120,
      121,
      140,
      163,
      168,
      169,
      174
    ],
    "narrower": [
      248
    ]
  },
  {
    "id": 248,
    "name": "Soft Tile and Brick",
    "confidence": 0,
    "category": "Outdoor Details",
    "broader": [
      125,
      168,
      207,
      215,
      218,
      228,
      233,
      243,
      247
    ],
    "narrower": [
      249,
      250
    ]
  },
  {
    "id": 249,
    "name": "Ornament",
    "confidence": 2,
    "category": "Ornamentation",
    "broader": [
      110,
      160,
      168,
      173,
      180,
      187,
      193,
      196,
      224,
      225,
      226,
      227,
      232,
      233,
      235,
      240,
      243,
      244,
      248
    ],
    "narrower": [
      218,
      234,
      250,
      253
    ]
  },
  {
    "id": 250,
    "name": "Warm Colors",
    "confidence": 2,
    "category": "Ornamentation",
    "broader": [
      135,
      182,
      199,
      207,
      233,
      235,
      238,
      240,
      244,
      248,
      249
    ],
    "narrower": [
      252
    ]
  },
  {
    "id": 251,
    "name": "Different Chairs",
    "confidence": 0,
    "category": "Ornamentation",
    "broader": [
      88,
      142,
      151,
      182,
      185,
      202,
      226
    ],
    "narrower": [
      252
    ]
  },
  {
    "id": 252,
    "name": "Pools of Light",
    "confidence": 2,
    "category": "Ornamentation",
    "broader": [
      129,
      130,
      135,
      146,
      151,
      179,
      182,
      183,
      185,
      229,
      250,
      251
    ],
    "narrower": []
  },
  {
    "id": 253,
    "name": "Things From Your Life",
    "confidence": 1,
    "category": "Ornamentation",
    "broader": [
      141,
      201,
      249
    ],
    "narrower": []
  }
] satisfies readonly PatternData[] as unknown as readonly Pattern[]
